exercism/ruby

palindrome-products/palindrome_products_test.rb

Change to assert_includes instead of assert collection.include?
Why? assert will only say if it passed or failed, the assert_includes will tell the user what was expected/ better errors

Change to assert_includes

---

gigasecond/example.rb
gigasecond/gigasecond_test.rb

Now shows the 46 hours and 40 seconds, rather than a date.
Re: #77

Looking for time not date objects

---

robot-name/robot_name_test.rb

In the README for this problem the letters are always in upper case. And
in the example solution, the `alphabet` method only returns upper case.
So I didn't think the tests needed to check for lower case letters.

Remove lower-case letters from regex

---

hamming/GETTING_STARTED.md

GETTING_STARTED.md was misleading when it mentioned the method needed "an argument" when it needs two arguments.  Since a lot of newbies start on this exercism, I thought it would be less frustrating if they don't get stuck on this step. :)

Correct number of arguments to set in getting started file

---

gigasecond/gigasecond_test.rb

I think it would make sense to change the tests to use UTC times to avoid daylight savings.
I copied the other tests when writing the "your birthday" test like so:
```ruby
def test_5_with_your_birthday
your_birthday = Time.new(1987, 3, 24)
gs = Gigasecond.from(your_birthday)
assert_equal Time.new(2018, 11, 30, 0, 46, 40), gs
end
```
I was surprised when it failed:
```
GigasecondTest#test_5_with_your_birthday [gigasecond_test.rb:31]:
Expected: 2018-11-30 00:46:40 +0000
Actual: 2018-11-30 01:46:40 +0000
```
but when I checked it, this made sense -- one gigasecond is 31y 259d 1h 46m and 40s, so the `01:46:40` is what I'd expect, not `00:46:40` like in the other tests. There's an hour missing somewhere!
It turns out that (on my UK-based machine) all the tests have the input time in British …

Use UTC in gigasecond exercise to avoid daylight savings issues

---

gigasecond/gigasecond_test.rb
largest-series-product/largest_series_product_test.rb
protein-translation/protein_translation_test.rb

Three of the exercise directories (gigasecond, largest-series-product and protein-translation) contain *_test.rb files which refer to the Minitest module rather than the MiniTest module. For consistency these references have been changed to MiniTest.

Make references to minitest module consistent across all exercises

---

difference-of-squares/difference_of_squares_test.rb

Since the API calls for a `Squares` object to be instantiated with a specific max value, it seems to be implied that the instance methods of a given instance should have the same result on subsequent calls. While not common, I have seen more than one submission that didn't have this property.

squares: subsequent calls should have same value

---

rna-transcription/complement_test.rb
rna-transcription/example.rb

I noticed that other language versions of this exercise handle argument errors
for the nucleotides.  This commit adds some new tests to check against bogus
nucleotides.

Add exception handling for wrong nucleotides.

---

hamming/hamming_test.rb

Original test name was: `def test_complete_hamming_distance_of_for_single_nucleotide_strand`
Proposed test name: `def test_complete_hamming_distance_for_single_nucleotide_strand`
Original test name was:  `def test_complete_hamming_distance_of_for_small_strand`
Proposed test name: `def test_complete_hamming_distance_for_small_strand`

Fix grammar on hamming tests

---

space-age/example.rb
space-age/space_age_test.rb

It's bad form to compare floats with each other using == and Exercism shouldn't be showing this to aspiring programmers.
[As the standard lib docs says](http://ruby-doc.org/stdlib-1.9.2/libdoc/minitest/unit/rdoc/MiniTest/Assertions.html#method-i-assert_in_delta) `asset_in_delta` should be used to compare floats.
The modified test pass with code designed for the old test (i.e. with `round(2)` after the division) and allows new code not to have to round the division which feels unnatural (it should not a responsibility of
`SpaceAge` to round its output).

Space Age: Don't compare floats using ==

---

robot-name/robot_name_test.rb

Consider a robot whose `reset` state is set to *true*, and this state is used to determine if a new name should be generated and returned. 
The current test suite will pass even if the programmer forgets to "unset" the robot's `reset` state after a call to name, thereby generating and returning a new name whenever the `name` method is called, ad infinitum. 
The proposed changes to the test suite would test that the `reset` state has been set to "off" or its equivalent.

Fix test suite for robot-name excercise

---

accumulate/accumulate_test.rb

Without this test, the test suite will pass even if #accumulate is altering the original object.
This is my first pull request to a public project, apologies if I made a mistake :-)

Accumulate: add test to forbid changing in place

---

SETUP.md

It will be better if the link to exercism help page for ruby is provided
in the README. In fact, it should be provided for other languages as
well.
Also make it clear that minitest is required for running the tests and
not for solving the exercise in particular.

Add link to exercism help in setup.md

---

grains/example.rb
grains/grains_test.rb

The current test suite requires new instances to be created by sending the `new` message to the `Grains` class. 
These new instances are exactly identical at time of creation, and won't differ in the future. It therefore doesn't make sense to create them. 
I have changed the test suite to test class methods instead of instances methods, and therefore avoid a solution that requires new instances. This rewrite is in keeping with the other exercises in the Ruby suite.

Modify tests so that identical instances are not necessary

---

circular-buffer/circular_buffer_test.rb

Tests for "CircularBuffer.write!" with "nil" argument and on non-full
buffers. Fixes #123.

Add tests for write! edge cases in Circular Buffer

---

.travis.yml

This change-set adds the `sudo` flag which allows travis to use containers rather than VMs, which means
much faster build allocation.

Use travis.ci containers for faster builds.

---

crypto-square/crypto_square_test.rb
crypto-square/example.rb

The tests for crypto-square expected incorrect rows in the normalised ciphertext, contradicting the README and other more conformant implementations. In addition the example itself was failing some of the existing (correct) tests.

Fixes the incorrect crypto-square tests

---

binary/binary_test.rb

Base on https://github.com/exercism/xruby/issues/135
I noticed while working on this solution that the case where a binary string is only numbers, i.e. 123 isn't covered. I noticed this while trying to determine if a string was valid I could pass the tests by doing something along the lines of:
```ruby
def to_decimal
return 0 if n.to_i == 0
n.reverse.each_char.with_index.map { |char, index| char.to_i * 2**index }.reduce(:+)
end
```
the test for string carrot123 returns 0, which is fine, but if i put 123 as a string my method would return a value,11 in this case.

Add numeric string test

---

hello-world/GETTING_STARTED.md
hello-world/hello_world_test.rb

The file `GETTING_STARTED.md` was moved from the hamming directory to the hello-world directory.
The `rescue from LoadError` was moved from `hamming_test.rb` to `hello_world_test.rb`.
I also updated the `GETTING_STARTED.md` to walk the user through how to solve the first test. I made the first test the one that has the user solve for `HelloWorld.hello` because is the simplest.
I can change it back to the empty string test if we want `HelloWorld.hello` to be extended functionality, but expecting to write the solution for `HelloWorld.hello('")` as the code `"Hello, !" is pretty confusing initially. I think it should start with either "Hello, World!" or "Hello, Alice!" in that case. I took the liberty of fixing a couple of sentences that sounded confusing when I was reading them.
Please give …

Moves the 'file not found' and getting_started from hamming and updates the getting_started.md

---

simple-linked-list/example.rb
simple-linked-list/simple_linked_list_test.rb

I'm submitting this on behalf of @zvkemp in order to close https://github.com/exercism/xruby/pull/83

prevent empty linked lists from being represented as nil

---

lib/disable_skip.rb

Use this to disable skip directives in the tests so we don't need to
remember to replace or delete code while we are evaluating.

Convenience library

---

.rubocop.yml

I prefer to have commands use a hyphen rather than snake case, but rubocop complains
about things like generate-hamming.

Exempt bin directory from style violations

---

hello-world/hello_world_test.rb

The hello world test suite triggered "long line" violations.
This uses a heredoc to move the actual failure message below the assertion.
Another option would have been to assign a temporary variable on the line above the assertion.

Fix style violations in hello world

---

nth-prime/nth_prime_test.rb

The error message is a string, but it was defined as an array. The style violation that it triggered was that the array should have a comma after the last element. Instead of fixing that, I decided to make the constant a string right off the bat.

Fix style violation in nth prime

---

robot-name/robot_name_test.rb

Rubocop was complaining about a long line. At first I changed
the failure message to be a heredoc, which triggered a "long method"
violation.
This feels a bit dirty, in that the method is legitimately long, but
perhaps it's not too bad to make the message a constant.

Fix style violations in robot-name

---

acronym/acronym_test.rb
acronym/example.rb

This may or may not be a good idea. It's not very idiomatic Ruby, but
in this case I think that it's very easy to read, and serves well as documentation.

Make acronym table-driven

---

.travis.yml

```text
_- Formatter flag
/ _- Simple Format
//  _- Display Cop Names
//  /
-fs -D
```
Gives a report like this:
```text
== Rakefile ==
C:  2: 81: Metrics/LineLength: Line is too long. [90/80]
```

The options give a more compact report

---

hello-world/hello_world_test.rb

For Minitest less than version 5.0.0 the error states "Missing
Dependency" and for the first error, it states "Error" as eluded to in
the message.

Clarify dependency or error.

---

Makefile
custom-set/custom_set_test.rb
custom-set/example.rb
lib/disable_skip.rb

re: #158
This first step is to reveal the skips that are not disabled allowing
bad example code through our checks.
To allow for this, the monkey patch on Skip should adhere to the
contract set forth in `Minitest::Assertions`
The Makefile is now using the same process for disabling skips.

Allow tests to reveal broken problem examples

---

.rubocop.yml
ocr-numbers/ocr_numbers_test.rb

The trailing whitespace is part of the spec for the numbers. Each number is defined as a grid.
Addresses (perhaps only in part) #158

Add trailing whitespace back to ocr-numbers

---

largest-series-product/example.rb
largest-series-product/largest_series_product_test.rb

Does not rely on on any specifically named 'helper' methods.  Tests
things through the implementation via public facing API
re: #10 
I removed the test for "identity" as well, as there was nothing that indicated that a empty string should return 1, which is what the test stated.
The example file was changed against the original specification provided by the README and the tests prior to these changes.

No longer drives the solution

---

binary/binary_test.rb
binary/example.rb

This adds some additional test cases to clarify the behavior around
the conversion of valid/invalid binary input.
See https://github.com/exercism/x-common/issues/95

binary: Add error handling

---

circular-buffer/circular_buffer_test.rb

it's a little bit more concise to read without have `String(i)` and you see the `'quotation marks'` instead

change ranges to use string versions

---

hello-world/GETTING_STARTED.md

when running the test on an empty file on Windows (Ruby 2.2), there is an error that was not mentioned in this very first help text.  It is important to acknowledge it and reassure the exercist, so that they don't give up.

explicit reference to error on Windows

---

.travis.yml

There were some backwards incompatible changes that caused new offenses to be triggered
on CI, which in turn causes PRs to fail for reasons unrelated to the code they're changing.
I was going to fix the new offenses, but one of them is actually triggered by
a bug in the rubocop library (see https://github.com/bbatsov/rubocop/issues/2116), so this turned
out to require more time than I could spare for it today.

Pin rubocop to a known good version

---

rna-transcription/example.rb
rna-transcription/rna_transcription_test.rb

The current test suite checks for an `ArgumentError` on completely invalid input, but not partially invalid input. For example, this solution passes all of the existing tests but accepts input that has a mix of valid and invalid characters:
~~~ruby
class Complement
DNA_REGEX = /[CGTA]/
RNA_REGEX = /[CGAU]/
KEYS = {
'C' => 'G',
'G' => 'C',
'T' => 'A',
'A' => 'U'
}
def self.of_dna(dna)
raise ArgumentError unless dna.match(DNA_REGEX)
dna.gsub(DNA_REGEX, KEYS)
end
def self.of_rna(rna)
raise ArgumentError unless rna.match(RNA_REGEX)
rna.gsub(RNA_REGEX, KEYS.invert)
end
end
~~~
These additional tests might discourage novices from simply checking for the arguments present in the tests.

Add tests to Rna Transcription for partially invalid input.

---

food-chain/example.rb
food-chain/food_chain_test.rb

This would be the first part to address https://github.com/exercism/xruby/issues/179.
As a lot of people solves the _kata_ by just loading the file `song.txt` with either of `File.open` or `IO.read`, this version of the tests raises run-time error, explaining that the desired solution must be to generate the song verses with the program.
It is left to improve the wording in the [metadata](https://github.com/exercism/x-common/blob/master/food-chain.yml).

food_chain: An error is raised if File.open or IO.read are used.

---

food-chain/food_chain_test.rb

File.read was getting a not so great error message as mentioned in #181 and this adds the File.read to the collection of ways to read a file that should be disallowed nicely.

Add File read for great messages

---

gigasecond/gigasecond_test.rb

This way it is not one of the first failing tests seen.

Add skip to version test of gigasecond_test.rb

---

binary-search-tree/binary_search_tree_test.rb
circular-buffer/circular_buffer_test.rb
largest-series-product/largest_series_product_test.rb
linked-list/linked_list_test.rb
robot-simulator/robot_simulator_test.rb
simple-linked-list/simple_linked_list_test.rb

These are some of the warnings that come up if you use a version of rubocop that is higher than 0.31.0.

Remove unnecessary rubocop disablings

---

rna-transcription/rna_transcription_test.rb

Clarify the comments in the test for the version number so the user knows that they do not need to increment the version number

Update RNA_transcription version test comments to be more clear for user

---

gigasecond/gigasecond_test.rb

Found that users were getting confused by the version test and it's purpose. Goal is to make it clear to users that there only need to return the number that is asked. They do not need to bump the versions themselves at any point. We have also included a link to the ruby docs on contstants so if a user is curious at what they are inserting, they can read more about them.

Update gigasecond version test comments to be more clear for user

---

binary/binary_test.rb

Found that users were getting confused by the version test and it's purpose (see [ticket 188](https://github.com/exercism/xruby/issues/188)). Goal is to make it clear to users that there only need to return the number that is asked. They do not need to bump the versions themselves at any point. We have also included a link to the ruby docs on contstants so if a user is curious at what they are inserting, they can read more about them

Update binary version test comments to be more clear for user

---

acronym/acronym_test.rb

Found that users were getting confused by the version test and it's purpose (see ticket https://github.com/exercism/xruby/issues/188). Goal is to make it clear to users that there only need to return the number that is asked. They do not need to bump the versions themselves at any point. We have also included a link to the ruby docs on contstants so if a user is curious at what they are inserting, they can read more about them

Update acronym version test comments to be more clear for user

---

food-chain/food_chain_test.rb

Found that users were getting confused by the version test and it's purpose (see [ticket 188](https://github.com/exercism/xruby/issues/188)). Goal is to make it clear to users that there only need to return the number that is asked. They do not need to bump the versions themselves at any point. We have also included a link to the ruby docs on contstants so if a user is curious at what they are inserting, they can read more about them

Update food-chain version test comments to be more clear for user

---

hamming/example.tt
hamming/hamming_test.rb

Found that users were getting confused by the version test and it's purpose (see ticket https://github.com/exercism/xruby/issues/188). Goal is to make it clear to users that there only need to return the number that is asked. They do not need to bump the versions themselves at any point. We have also included a link to the ruby docs on contstants so if a user is curious at what they are inserting, they can read more about them.

Update hamming version test comments to be more clear for user

---

hello-world/GETTING_STARTED.md

Should use possessive pronoun 'its'.
Reference: http://grammarist.com/spelling/its-its/

Fixing grammatical error.

---

SETUP.md

I know this is extremely nitpicky, but... 'running' was missing an 'i'.

Correct typo in Ruby SETUP instructions

---

trinary/example.rb
trinary/trinary_test.rb

Previously, certain implementations of trinary could pass all of the
tests despite doing no validation on the input. This is because "a".to_i
(and any non-numeric character) is 0 in ruby, so an all alpha test
string will evaluate to 0. This commit adds a string that has numbers
mixed in with letters, to ensure that validation is required for tests
to pass. This also updates the example to do the required validation.

Add new test for trinary

---

custom-set/custom_set_test.rb

Adds some counterexamples to the equal test. Since defining equality is part of the solution, some implementations may pass the assert_equal test without really testing for equality (e.g. one implementation I wrote passed the assert_equal test but incorrectly allowed sets to be equal even if one had more elements).

Add refute cases to custom-set equal test

---

docs/RESOURCES.md

No longer using the `www` prefix for the home page on RubyLearning.com
fixes #230

RubyLearning DNS has changed

---

lib/generator.rb

In 7ec5c675610fe5981f8894fdd4ff9e61f00da30d all exercises were moved to
the `exercises/` directory. The generator needs to be able to know the
path a given exercise resides at to be able to read the template, write
version files, write the actual test file, etc. So we need to update the
generator to use the new path.
Tested by ensuring that bin/generate-* can be run after this change (it
would not be able to run before this change).
Note however that bin/generate-difference-of-squares wasn't able to run,
but that's a separate issue - the JSON file doesn't contain a top-level
"cases" keys like the generator expects. Instead the "cases" keys are in
"square_of_sum" and "sum_of_squares".

generator: look for files in exercises/ dir

---

exercises/simple-linked-list/example.rb
exercises/simple-linked-list/simple_linked_list_test.rb

This is an update to simple linked list to address the issues in #249.
Changes:
* We do not test reversing a list created from an empty array since `Element.from_a([]) # => nil`
* We stop testing `Element#next` for nil and start testing `Element#tail?`
* Split all the tests up into separate methods since previously many things were being tested in each test method.
* In the example we no longer need to use a NullObject pattern.
closes #249

Cleanup simple-linked-list

---

exercises/say/say_test.rb

in billion or million, there some missing cases I think, could be tested for "three hundred million" or "three hundred forty million", "three hundred fifteen million" etc (any of those digits in 10th or 11th place are 0, or the two digits ranged from 11 to 19)

Add more cases to say_test.rb

---

exercises/hello-world/GETTING_STARTED.md

The example gave an incorrect solution as the test was looking for 'Hello, World!' not 'Hello, world!'

edit GETTING_STARTED.md with proper case

---

exercises/sum-of-multiples/example.rb
exercises/sum-of-multiples/sum_of_multiples_test.rb

No default values, as nothing would be reasonable

---

exercises/binary/binary_test.rb

* Right now in `test_invalid_binary_numbers_raise_an_error` there is no
check for if the string passed in has a space and then invalid binary. i.e. `"001 yolo"`.
* The problem with this is that values that should be failing can pass
in someones code. For Example if someone was to use the regex
`/\b[01]+\b/` to validate the binary and the binary passed in was "001
yolo" it would still match 001 and not raise an error. This commit
just adds in the case where `"001 yolo"` is passed in to make sure it
raises an argument error still.

Add Binary test to account for when string has a space

---

exercises/circular-buffer/circular_buffer_test.rb

Removes tests for nil as content for the buffer
Fixes #257

Nil is not special objects in a circular buffer

---

exercises/clock/clock_test.rb

This has the non-comparitive tests implemented from the changes
implemented in the canonical changes introduced by @kytrinyx
references #282
references exercism/x-common#166

clock: Canonical Test Data improved, part 1

---

Makefile
exercises/binary/example.rb
exercises/difference-of-squares/example.rb
exercises/say/example.rb

The makefile had not been updated to run the files under their new /exercises
subdirectory.
As a result, we had example files that were failing the tests, but CI was passing.
This also fixes the exercises that were failing (binary, difference-of-squares, say).
See https://github.com/exercism/xruby/pull/277

Fix tests for CI

---

bin/enable-executable
bin/executable-tests-check

add bin/* files to `enable-executable` and `executable-status-check`
generator now makes test files executable
make `enable-executable` chmod consistent with current file modes

file mode changes

---

exercises/pangram/example.tt
exercises/pangram/pangram_test.rb

This should fix an issue @callahat reported in ruby 1.9.3.
A `grep --color=auto --exclude-dir=.git -nrP [^[:ascii:]]` finds this:
```
docs/ABOUT.md:3:Ruby was created as a language of careful balance. Its creator, [Yukihiro “Matz” Matsumoto](https://en.wikipedia.org/wiki/Yukihiro_Matsumoto), blended parts of his favorite languages (Perl, Smalltalk, Eiffel, Ada, and Lisp) to form a new language that balanced functional programming with imperative programming.
README.md:46:├── x-common
README.md:47:└── xruby
exercises/pangram/pangram_test.rb:36:    str = 'Victor jagt zwölf Boxkämpfer quer über den großen Sylter Deich.'
```
This exercise is the only non-ascii character present in a ruby file.

specify utf-8 enconding for pangram exercise

---

exercises/binary/binary_test.rb

This is my first contribution (yay!) closing issue #275.
Some of the edge cases mentioned in the issue were already present, so I just added alphabet characters in the middle of a valid binary number (`10nope10`) and an invalid number on its own (`2`).

binary: Add invalid edge case tests. Closes #275

---

docs/TESTS.md

We give the clients the nicety of not flooding them with errors and
failures when they fetch the lessons, but with this, we inform them how
they can control the skip behaviors, and how they can test individually
on demand.
fixes #297

Giving the users the power of Skips

---

exercises/food-chain/food_chain_test.rb

This restricts use of IO.read and File.read in class- and instance of
class- name space for FoodChain class.

Restricted use of File.read in class name scope

---

exercises/robot-name/robot_name_test.rb

Use refute_equal (rather than assert !=) in order to return a more helpful error message on test failure.

Robot-Name: Better error message on test failure.

---

exercises/nth-prime/nth_prime_test.rb

Fix #352 
This constraint was throwing an error in new Ruby versions, quoting @Cohen-Carlisle :
> I favor removal of the anti cheat as impacting a non cheating user is worse than not catching a cheating user.

[nth-prime] Remove constraint on Prime class usage.

---

exercises/leap/example.tt
lib/leap_cases.rb

There was no failure message supplied by the test case generator, so all tests had a blank failure message.
This patch adds an informative failure message for each test based on the test input and expected values.
Fixes: #366

Leap generator fix

---

lib/generator.rb

Change git log format from 'oneline' `"%h %s"`, to abbreviated hash only `"%h"`
The code for generated tests often includes a comment giving the git version of the test data from which the test was generated, such as:  
`# deb225e Implement canonical dataset for scrabble-score problem (#255)`
The same version string is used for all tests generated at that time and will often have no relevance to the test you are looking at and only adds confusion.
"Why is it telling me about scrabble-score? This is the test file for hamming!"
By including only the hash, anyone interested enough in the commit can easily look up the exact commit message and everybody else can just ignore what appears to be a random hexadecimal string.

Generator: Remove commit message subject from git version indicator.

---

exercises/binary-search-tree/binary_search_tree_test.rb
exercises/binary-search-tree/example.rb

Ruby's core collections all have `#each` return an enumerator when the method doesn't get a block. Bst should do the same, so I updated the tests and example.rb to reflect this.

Bst each should return enumerator

---

exercises/leap/example.tt
exercises/leap/leap_test.rb

Regenerated the leap tests to add in the test failure error messages.
Since the tests themselves have not changed the BookKeeping version number has not been incremented.
Actually fixes #366 (#367 fixed the generator but did not include the updated test file.)

Leap: Add failure messages to tests

---

exercises/perfect-numbers/perfect_numbers_test.rb

`require_relative 'example'` is in `perfect_numbers_test.rb`.
It should be `require_relative 'perfect_numbers'`.

Fix 'require_relative' directive in perfect_numbers_test.rb

---

exercises/trinary/example.rb
exercises/trinary/trinary_test.rb

Solutions that check for decimals in "normalization" should be stricter
than simply checking for decimals.

Trinary: Test for 4, as invalid trinary value

---

exercises/hello-world/GETTING_STARTED.md

Simple typo in the GETTING_STARTED.md guide for the Hello World exercise. Steps were numbered 1, 2, 3, 4, 6. Now they are 1, 2, 3, 4, 5.

Corrected numbering for step 5

---

exercises/grade-school/example.rb
exercises/grade-school/grade_school_test.rb

Change the data structure returned by `students_by_grade` in order to
adhere to the "sorted list" criteria specified in the readme.
Rename `grade` method to `students`.
Update version number.
In the example solution, rename `grade` parameter to `level` to try to
eliminate confusion due to multiple different usages of `grade`.

Change `students_by_grade` data structure. (+more) Closes #389

---

exercises/binary/binary_test.rb
lib/binary_cases.rb

Resolves #404 
With changes proposed at exercism/x-common#303 and based on test data proposed at exercism/x-common#305.
This PR includes two changes:
* Re-generate tests from exercism/x-common
* Remove compound assertion logic from BinaryCases since all tests with multiple assertions have been split into separate tests.
Thank you so much for your time and feedback!

Re-generate binary tests with split assertions

---

exercises/wordy/wordy_test.rb

As you can see in the README file, you must ignore arithmetical
precedence rules and calculate as you move forward each step.

Add a more helpful test failure message

---

SETUP.md

Add space to command between flag and argument so it is clearer what the command does.

Fix typo in SETUP.md

---

exercises/scale-generator/example.rb
exercises/scale-generator/scale_generator_test.rb

Maybe there's a reason to write all flats with `%` and all sharps with `[]`. Otherwise, I think would be better to unify criteria. Idem about scale names.
Please have a look and let me know.
Thanks!.

Possible changes in scale-generator

---

exercises/list-ops/example.rb
exercises/list-ops/list_ops_test.rb

Hey,
I've found a couple of inconsistencies here. Some `assert` should be `assert_equal`, and fixing that, I've realized that some tests doesn't pass anymore. So I'm proposing those changes.
Please have a look and let me know.
Thanks!

Fix tests and example [list-ops]

---

exercises/triangle/triangle_test.rb

As discussed at exercism/x-common#311 and exercism/x-common#375 here are my proposed updates to the tests which reflect the canonical-data.json.

Triangle: Update tests to match canonical-data.json.

---

exercises/gigasecond/example.rb

The Gigasecond from method does not require that it be given a time
object, only that the object given responds to + and works with numbers.
The README supports this by avoiding any mention of specific "type" of
return, only mentioning "a moment".

Gigaseconds example code simplified

---

README.md
bin/generate
bin/generate-acronym
bin/generate-alphametics
bin/generate-binary
bin/generate-bracket-push
bin/generate-clock
bin/generate-connect
bin/generate-custom-set
bin/generate-difference-of-squares
bin/generate-gigasecond
bin/generate-hamming
bin/generate-hello-world
bin/generate-largest-series-product
bin/generate-leap
bin/generate-nth-prime
bin/generate-pangram
bin/generate-raindrops
bin/generate-rna-transcription
bin/generate-roman-numerals
bin/generate-run-length-encoding
bin/generate-two-bucket
lib/bracket_push_cases.rb
lib/raindrops_cases.rb

While creating a generator for acronym and noticed how each exercise had it own generate script. This leads to a lot of code duplication since each script is almost identical. 
This PR would allow for a single generate script that takes an exercise name as the argument, and regenerates the exercise.  If the exercise is not found and error message will display.  I tested it out on all the exercises and I had to modify two generators to ensure consistent naming.
Example usage:
`bin/generate raindrops`
Let me know if this is something that would be helpful!

Common generate script

---

exercises/acronym/acronym_test.rb

Remove rubocop:disable comment from `acronym_test.rb`
Addresses issue "Remove rubocop magic comments from user facing files #385"
(This PR is a simple example for any beginners working on #385)

[acronym] Remove rubocop:disable comment.

---

exercises/word-count/example.tt
exercises/word-count/word_count_test.rb
lib/word_count_cases.rb

In the list of exercises that need a generator #396 , I saw word-count. Once I started working on it, I found the template `exercises/word-count/example.tt ` but I couldn't find any generator associated to it, so I decided to modify the current template and create the generator that you can see in this PR.
The `canonical-data.json` file from x-common has less examples that the current version of `word_count_test.rb` Should I add these examples to x-common?

Add word count generator

---

bin/enable-executable
bin/executable-tests-check

Use path relative to the executable Ruby file in the xruby 'bin' directory rather than the current working directory which was the default behaviour.
This will enable the commands to be run from any working directory and still be able to access the files they need to check/update.
fixes #291

Bin files independent of pwd  (Fixes #291)

---

exercises/allergies/allergies_test.rb
exercises/atbash-cipher/atbash_cipher_test.rb
exercises/beer-song/beer_song_test.rb
exercises/binary-search-tree/binary_search_tree_test.rb
exercises/binary/example.rb
exercises/circular-buffer/circular_buffer_test.rb
exercises/clock/example.rb
exercises/connect/connect_test.rb
exercises/custom-set/custom_set_test.rb
exercises/diamond/diamond_test.rb
exercises/etl/etl_test.rb
exercises/house/house_test.rb
exercises/largest-series-product/example.tt
exercises/largest-series-product/largest_series_product_test.rb
exercises/linked-list/linked_list_test.rb
exercises/meetup/meetup_test.rb
exercises/nth-prime/example.tt
exercises/nth-prime/nth_prime_test.rb
exercises/ocr-numbers/ocr_numbers_test.rb
exercises/protein-translation/protein_translation_test.rb
exercises/proverb/proverb_test.rb
exercises/queen-attack/queen_attack_test.rb
exercises/robot-simulator/robot_simulator_test.rb
exercises/strain/strain_test.rb

Addresses issue "Remove rubocop magic comments from user facing files #385" for the rest of the files within `exercises/`
Rubocop still shows no errors with these inline comments removed.

Remove rubocop:disable comments from exercises/

---

exercises/isogram/isogram_test.rb
lib/isogram_cases.rb

When the first test case is generated it leaves out the 'skip' But the
line still contains the whitespace present in the template file.
Add commented out skip to avoid having trailing whitespace.
I'm not sure this is an improvement, but it does provide the solver with
a hint about what they're supposed to do with the skips to make the
tests run.

[isogram] Eliminate trailing whitespace in test file.

---

bin/generate

Give usage instructions when bin/generate is called with no arguments.
The instructions also provide a list of the available generators.
Edit: Here's what it looks like:
``` shell
$ bin/generate 
Exercise name required!
Usage: bin/generate exercise_generator
Available exercise generators:
acronym alphametics binary bracket_push clock connect custom_set difference_of_squares gigase
cond hamming hello_world largest_series_product leap nth_prime pangram raindrops rna_transcri
ption roman_numerals run_length_encoding sieve two_bucket
```

bin/generate usage instructions.

---

lib/generator.rb

If you have a template that contains a value that might be nil or an empty string such as:
```
<%= test_case.comment %>
```
You often do not want a blank line appear in the output if there is no comment.
This patch changes the ERB setttings so that these blank lines are not included in the output. 
This may cause minor issues where this behaviour has been relied on such as templates that expect a Ruby syntax related 'end' to insert a blank line.
```
<% end %>
```
But these are easily fixed by inserting a new blank line into the template.
Technical details:
It does this by setting the ERB *trim_mode* to '<>'
'<>' omits newline for lines starting with <% and ending in %>
See also: http://ruby-doc.org/stdlib-2.1.1/libdoc/erb/rdoc/ERB.html#method-c-new

lib/generator.rb: Ignore blank template lines.

---

exercises/bowling/example.rb

By default the example.rb was raising a `RuntimeError` which caused the pre-push test run to fail.

Bowling: Make error raised by example match error expected by tests.

---

README.md

Related to: https://github.com/exercism/xruby/issues/452 and https://github.com/exercism/xruby/pull/463
Updates the README to include information about the generator interface.  This way the README has up to date information before https://github.com/exercism/xruby/pull/463 is merged.

Update README with Exercise Generators

---

Gemfile
Rakefile
bin/executable-tests-check
config.json
lib/generator.rb
test/generator_test.rb
test/test_helper.rb

Adds unit tests for `lib/generator` In order to make development on the test generator easier and less scary.
The tests can be run via: `bundle exec rake test`
In order to get this set up a few other things need to happen:
Add `rake` gem for easy test running.
Add `simplecov` gem to provide test coverage reports.
Create `test/` directory to hold the tests.
Exclude `test/` directory from executable tests check.
Create `test/generator_test.rb` to hold unit tests of `lib/generator.rb`
Once that was done I was able to start writing some unit tests. 
I have added a configurable `metadata_repostitory_path` in order to aid testing by being able to supply a test fixture rather than having to rely on the global x-common data.
Not much else is covered so far this shall be improved in future PRs. …

Start unit testing lib/generator

---

lib/generator.rb
test/generator_test.rb

Add test coverage for `sha1` method
Extracted `GitCommand` class to wrap the required git shell commands.
There's currently only one, `short_sha`.
We're using this instead of a gem because we don't need the full suite of git functionality and:
The 'git' gem is umaintained and doesn't provide short shas.
The 'rugged' gem requires compiling its own libgit2 which seems like an excessive dependency.

Improve lib/generator test coverage

---

.rubocop.yml

In the process of working on some test generators, I ran into a little issue with the current rubocop and using keyword arguments.
Here I just added a target ruby version the rubocop config. I set the target version to `2.1`, but that was only to make keyword arguments. I'm not sure if that's the actual version we want to target, or if it really matters.
Thanks so much for your time!

Add TargetRubyVersion for rubocop

---

README.md

Making another PR to update the README based on #511
The [Gemfile](https://github.com/exercism/xruby/blob/master/Gemfile) doesn't specify a Ruby version, but would you like me to add it there? If so, should I use `2.1.2`, which is what CI runs on?

Update README to use Ruby version 2.1

---

test/test_helper.rb

Hi there!
I noticed a little typo in the `SimpleCov` configuration that causes test files to not be filtered out.
The effects of this can be reproduced by adding a new test file `foo_test.rb`:
```ruby
require_relative 'test_helper'
```
and running `rake test` to regenerate the coverage map.
This will cause `test/generator_test.rb` to show up under the `Utilities` tab and the `All Files` tab in the coverage web view.

Fix typo in SimpleCov filter

---

Gemfile

Looks like a new version of the gem `rainbow` was released today and is causing some problems with our travis builds.
There's an issue already on the rainbow repo at sickill/rainbow#40.
This should ensure that we use rainbow version `2.1.x` and not the currently problematic `2.2.0` version.

Limit rainbow gem version

---

Gemfile

Resolves #517
It looks like rainbow version `2.2.1` has been released and is working for some, but not others (maybe a different issue than the original).
In this PR I removed `rainbow` from the Gemfile and removed the `--queit` flag from `bundle install --quiet` in the Travis config to make sure `2.2.1` was being used and it worked!
I then went ahead and reverted the temporary commit to include a specific version in the Gemfile.
Thanks so much for your time!

Remove rainbow from Gemfile

---

Makefile

Hi there!
I noticed while looking at the Travis CI output yesterday that the tests don't appear to be running.
From Travis CI log output:
```
$ make test
```
```
make: `test' is up to date.
The command "make test" exited with 0.
```
This is happening because we added a `test` directory, and the Makefile target is also named `test`.
If this looks good to you all and gets merged, I will rebase and push #514, #510, and #509 to run CI with the tests.
Thanks so much for your time!

Add phony target for test in Makefile

---

.travis.yml
test/test_helper.rb

This PR adds `rake test` to the travis config to run non-exercise tests in CI as discussed in #519.
Resolves #519.

Run non-exercise tests in CI

---

test/grains_cases_test.rb
test/wordy_cases_test.rb

These two tests use the `.to_json` method which is defined in the JSON module, which needs to be `require`d before it is used.
Previously they were relying on an unspecified file to have loaded the module for them, but the module was not guaranteed to be loaded before the tests ran so the tests would fail.

*_cases_tests: Require 'json' module before calling `.to_json`

---

test/test_helper.rb

Right now, code coverage isn't being generated properly.
This is because `simplecov` is initialized after `minitest/autorun` is required.

Move simplecov code before minitest is required

---

lib/tasks/exercise_test_tasks.rb
lib/tasks/exercise_tests_runner.rb

Replaced private attr_reader methods with direct instance variable access. This is not as elegant as the attr_reader version, but does not generate interpreter warnings.
The warnings were:
```
xruby/lib/tasks/exercise_tests_runner.rb:23: warning: private attribute?
xruby/lib/tasks/exercise_tests_runner.rb:23: warning: private attribute?
xruby/lib/tasks/exercise_test_tasks.rb:24: warning: private attribute?
xruby/lib/tasks/exercise_test_tasks.rb:24: warning: private attribute?
```
These warnings are present in Ruby versions < 2.3.0

rake task tests: Fix Ruby warnings due to private attr_reader.

---

lib/generator/command_line.rb
lib/generator/repository.rb
test/generator/repository_test.rb

The old behavior was:
```
$ bin/generate isogram
$
```
Which is not particularly friendly or helpful. Did it even do anything?
The new default behavior is to report success to stdout:
```
$ bin/generate isogram
Generated isogram tests version 3
$
```
The original behavior can be replicated by redirecting stdout to /dev/null
```
$ bin/generate isogram > /dev/null
$
```
The `-v` option still provides additional information.
```
$ bin/generate -v isogram
Incremented tests version to 4
Updated version in example solution to 4
Generated isogram tests version 4
```

bin/generate: Default display success message.

---

.rubocop.yml
bin/enable-executable
bin/executable-tests-check
exercises/connect/example.rb
exercises/diamond/example.rb
exercises/simple-linked-list/simple_linked_list_test.rb
lib/all_your_base_cases.rb
lib/alphametics_cases.rb
lib/generator/files.rb
lib/generator/files/track_files.rb
lib/grains_cases.rb
lib/isogram_cases.rb
lib/pangram_cases.rb
test/fixtures/xruby/lib/alpha_cases.rb
test/generator/command_line_test.rb
test/generator/template_values_test.rb

@kotp flagged a missing space after comma in a review: https://github.com/exercism/xruby/pull/540#pullrequestreview-16715930
This patch enables the Style/SpaceAfterComma cop so that this can be automatically detected and fixed by Rubocop.

Rubocop: Enable space after comma cop

---

README.md

The various file names and file paths for generators have changed, both in the x-common repository, and in the xruby repository.
In order to make it easier to follow, this breaks the documentation into three logical sections targeting the tasks that the reader will likely want to choose from:
* regenerating the exercise
* changing a test suite
* implementing a new generator

Update documentation about generated test cases

---

exercises/hello-world/example.tt
exercises/hello-world/hello_world_test.rb
lib/hello_world_cases.rb

Update the hello-world generator to use the standard generator method names.
Use the standard `workload` and `skipped` methods rather than the more ambiguous and template dependent `do` and `skipped?` methods.
Regenerated `hello-world_test.rb` which was almost identical to the original version.
* Change from sigle quotes to double quotes due to use of `inspect`
* Addition of commented out `#skip` call which now matches other generated tests.

Standardize hello-world generator.

---

exercises/anagram/example.tt
exercises/bowling/example.tt
exercises/hamming/example.tt
exercises/rna-transcription/example.tt
lib/anagram_cases.rb
lib/binary_cases.rb
lib/bowling_cases.rb
lib/hamming_cases.rb
lib/rna_transcription_cases.rb

We have standardized on `workload` for the method name that generates the body of a test.
`work_load` was used a few times prior to the standardization.
This PR updates these old usages to help avoid confusion.

Rename 'work_load' to 'workload'

---

README.md

Update the readme to better reflect the current best practices for test
generators.

Update test generator documentation.

---

exercises/linked-list/linked_list_test.rb

Adds tests to test if the opposite end of the Deque is nulled correctly when popping/shifting leaves the list empty.
---
The tests for the [Linked List exercise](https://github.com/exercism/xruby/tree/master/exercises/linked-list) don't yet test if, when popping or shifting should leave the list empty, the reverse end of the list is cleared/nulled correctly. When the list is empty, both the head and the tail ends should be empty/null.
Forgetting to do that is an easy mistake to make when implementing a doubly linked list, and the current test suite doesn't cover that yet.
This PR adds the tests for that, without the need to define the behaviour for error conditions (`pop` or `shift` on an empty list).
---
Closes #562.

Linked list: add tests for emptied list.

---

README.md

Add a workload philosophy section to `Readme.md`
The Workload philosophy section gives some information about why an
educational workload layout is preferable to a concise one liner.
Inspired by: https://github.com/exercism/xruby/pull/567#pullrequestreview-34227224

Documentation: Readme - Add workload philosophy section.

---

lib/generator/template_values.rb
lib/generator/test_template.erb
test/fixtures/xruby/lib/generator/test_template.erb
test/generator/template_values_test.rb

This reverts commit e43b6f4560a737afba004676e6434375ec276384.
I'm not sure this is the right thing to be doing, removing it from master until we can work out if it is.

Revert "extract template metadata into own class"

---

lib/generator/files.rb
lib/generator/files/metadata_files.rb
test/generator/files/metadata_files_test.rb
test/generator/files_test.rb

Add query for the version of the canonical-data for a problem. `CanonicalDataFile#version`
The version string comes from the 'version' key of `canonical-data.json` file. 
It is a requirement that all canonical-data files have this key.
Having this will enable future use of this value for test automatic version detection/updating.
This patch also includes a refactoring which extracts a `Generator::Files#read` method which is a wrapper around `File.read(filename) if File.exist?(filename)`
This makes it possible to easily stub file reads during testing to reduce reliance on fixture files as part of the unit testing process.
See also: 
https://github.com/exercism/x-common#test-data-format-canonical-datajson
https://github.com/exercism/x-common#test-data-versioning

Add query for version of canonical data

---

.github/stale.yml

Change will have Probot label stale issues with "stale" rather than "wontfix"

Probot: Changes "wontfix" to "stale" from default

---

test/generator/files/metadata_files_test.rb

This reverts commit 4f572e8e4bd3913f530439fdf4d3bfcc144d9aa6.
This change worked on Ruby 2.2 but stopped working from ruby 2.3 due to
changes in the way OpenStruct works.
See also:
http://stackoverflow.com/questions/39278864/openstruct-issue-with-ruby-2-3-1
minimal example: https://gist.github.com/anonymous/162dd5466b23331e0e31b891ac61d337

Revert "Simplify test for MetadataFiles#canonical_data"

---

exercises/run-length-encoding/.meta/generator/run_length_encoding_cases.rb
exercises/run-length-encoding/run_length_encoding_test.rb

Resolves #588 
* Update the test generator to add `encode_` or `decode_` as a prefix to all tests depending on the method being tested.
This fixes a name collision bug between:
def `test_empty_string` for encode
and
def `test_empty_string` for decode
* Regenerated tests.

run-length-encoding: Add property to generated tests

---

lib/generator/exercise_case/assertion.rb
test/generator/exercise_case/assertion_test.rb

Minitest will emit a warning if `assert_equal` is used when the expected value is `nil`
This patch updates the cases generator to use `assert_nil` instead of `assert_equal` when the expected value is `nil`

exercise_cases: Use assert_nil when expected is nil

---

README.md

Add some missing elements:
require statement
`Generator` namespace

Readme: Update default generator example.

---

exercises/alphametics/.meta/generator/test_template.erb
exercises/bowling/.meta/generator/test_template.erb
exercises/connect/.meta/generator/test_template.erb
exercises/dominoes/.meta/generator/test_template.erb
exercises/hello-world/.meta/generator/test_template.erb
exercises/leap/.meta/generator/test_template.erb
lib/generator/template_values.rb
lib/generator/test_template.erb
test/generator/template_values_test.rb

The version string comes from the 'version' key of the canonical-data.json file.
It is a requirement that all canonical-data files have this key.
Displaying this version makes it easier to see which version of the canonical tests were used to generate a particular test file.
This patch does not regenerate the tests to include this version information, but it will be included next time the tests are generated.
Ref: https://github.com/exercism/xruby/issues/485

generators: Add canonical data version to test templates

---

lib/generator/files/track_files.rb
test/generator/files/track_files_test.rb

Part of generator improvements (exercism/xruby#485)
Last step in moving test templates to `.meta`.

generator: remove support for legacy test template location

---

lib/tasks/exercise.rb
test/tasks/exercise_test.rb

Fixes bug introduced in #605 which did not check in the right place for the existence of the example file when deciding which version of the example file to use.
The bug is fixed as part of #607 : https://github.com/exercism/xruby/pull/607/commits/1bca6eace6a1523c39aa51ae386b468792acffaf but this PR separates out the change and implements a unit test for it, verifying that the stubbed out `File.exist?` method is called with the correct filename.

tests: Check in the correct location for the example file.

---

exercises/phone-number/phone_number_test.rb

`phone_number_test.rb` lost its canonical data version number in all the excitement yesterday.
This patch adds it back in.

phone-number: Re add canonical_data_version

---

config.json

When https://github.com/exercism/configlet/pull/13 is merged, configlet will support alternate patterns for specifying the example solution filename.
This is done via the "solutionpattern" key.
The value `"\\.meta/solutions/[^/]*\\.rb"` ensures there is a `.rb` file in the `.meta/solutions` directory for a problem.
(double backslashes are required due to JSON escaping.)
It's not critical to check the exact name of the file, just that there is at least one ruby file which we can assume is a valid solution file. (Otherwise PR reviewers are being too slack.)
Merging this early should have no negative effects to the current version of configlet, but does risk (very small chance) there being other incompatible changes to configlet before this PR is merged.
Oh, and it requires synchronisation …

config.json: Add alternate solution location pattern.

---

exercises/alphametics/.meta/generator/test_template.erb
exercises/bowling/.meta/generator/test_template.erb
exercises/connect/.meta/generator/test_template.erb
exercises/dominoes/.meta/generator/test_template.erb
exercises/hello-world/.meta/generator/test_template.erb
exercises/leap/.meta/generator/test_template.erb
lib/generator/case_values.rb
lib/generator/exercise_case.rb
lib/generator/test_template.erb
test/fixtures/xruby/exercises/alpha/.meta/generator/alpha_cases.rb
test/fixtures/xruby/exercises/alpha/.meta/generator/test_template.erb
test/fixtures/xruby/lib/generator/test_template.erb
test/generator/case_values_test.rb
test/generator/exercise_case_test.rb
test/generator/template_values_test.rb

Part of the Generator Improvements: exercism/xruby#485
Changes:
* Convert the default `test_template.erb` to include the index in the iterator (with test changes, etc)
* Update the six custom test templates in the same way
* Stop injecting index as a case value
* (and cleaned up a fixture/test that was leftover from the cases proc logic)
Testing:
* `rake test`
* regenerated test suites for all six exercises with custom test templates, no changes
* regenerated test suites for a sample of other exercises, no changes

generator: remove requirement for test case to know its index

---

config.json
exercises/robot-name/.meta/solutions/robot-name.rb
exercises/robot-name/HINTS.md
exercises/robot-name/robot_name_test.rb

The robot name description [has been updated](https://github.com/exercism/x-common/pull/765)  to clarify that name uniqueness is a requirement.
> The names must be random: they should not follow a predictable sequence.
Random names means a risk of collisions. Your solution must ensure that
every existing robot has a unique name.
This PR updates the tests and example solution to match this.
Because the new problem is significantly harder than the old version it has been moved down in the order of problems.
A HINTS.md file has been added to specify the `forget` method used to aid in testing.

robot-name: Updated based on clarified description.

---

test/fixtures/xruby/exercises/alpha/.meta/solutions/alpha.rb
test/generator/files/track_files_test.rb
test/generator/repository_test.rb

Fixes #628 
The tests that were erroneously passing in #625 at https://github.com/exercism/xruby/commit/e0e6eb5054a815b16eff746001f63f57f20a16b8 and before would now fail until everything is made right in https://github.com/exercism/xruby/pull/625/commits/19987a218dd7392e8b385b669e8e42ca2f534bbb
Do not mock the system under test!
The pattern I was using for testing here would be appropriate for a class correctly using composition, but led to the test failures here when includes are being used to try and achieve a similar result.

generator: Fix (some) test deficiencies

---

lib/generator.rb
lib/generator/command_line.rb
lib/generator/exercise.rb
lib/generator/files.rb
lib/generator/files/metadata_files.rb
lib/generator/files/track_files.rb
test/generator/exercise_test.rb
test/generator/files_test.rb
test/generator_test.rb

Step 1 in separating out the Repository and Exercise models
(see also exercism/xruby#633)

generator: rename Repository model

---

exercises/trinary/trinary_test.rb

I noticed that the trinary test didn't automatically skip the book keeping test.
This pull request fixes that.

Add missing skip in trinary_test

---

test/generator/underscore_test.rb

https://github.com/exercism/xruby/pull/583 Added a refinement to `Fixnum` to convert integers into their underscored string representation.
This PR adds a unit test to bring us back up to 100% test coverage.

Test Fixnum#underscore

---

lib/generator/command_line/generator_optparser.rb
test/generator/command_line/generator_optparser_test.rb

Resolves #644 
In #583 there was a problem with the generator not being found:
```
$ bin/generate space-age
A generator does not currently exist for space-age!
```
This patch adds a bit more information to the error message about where the generator expected to find the file it needs.
```
A generator does not currently exist for space-age!
Expecting it to be at: <user_specific_path>/exercises/space-age/.meta/generator/space_age_case.rb
```

Be more helpful when generator can not be found

---

LICENSE
README.md

We don't need the duplication, especially now that the GitHub interface shows the
license information on the main page of the repository when it can be detected
directly from the LICENSE file.
This also updates the LICENSE to reassign the copyright to the Exercism legal entity (which I finally got my act together and created).

Update license information

---

exercises/triangle/.meta/generator/triangle_case.rb
exercises/triangle/triangle_test.rb

To make it possible to see from the failure message which triangle is being tested/failing.  #653 
Provided the parameters that are being tested in the error message for a more informative message. 
So instead of:
```
1) Failure:
TriangleTest#test_equilateral_triangle_sides_may_be_floats [ruby/triangle/triangle_test.rb:36]:
Expected 'true', triangle is equilateral.
```
You would see:
```
Expected 'true', triangle [0.5, 0.5, 0.5] is equilateral.
```
Created a Triangle class that would fail the tests to produce the errors. Please see the screen shot below for the outputs. 
- n/a Bug fix (non-breaking change which fixes an issue)
- n/a Breaking change (fix or enhancement that would cause existing functionality to change)
- n/a Gardening (code and/or documentation cleanup)
- n/a My change …

Provide parameters in test failure message for Triangle exercise

---

README.md

When I was trying to regenerate the test suites I was getting the error: 
```
/Users/alexanderdelgado/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- require_all (LoadError)
from /Users/alexanderdelgado/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
from /Users/alexanderdelgado/Developer/open-source/xruby/lib/generator.rb:1:in `<top (required)>'
from /Users/alexanderdelgado/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
from /Users/alexanderdelgado/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
from bin/generate:4:in `<main>'
```
@Insti let me know that it was because I needed the `require_all` …

Update Generated Test Suites section in README with gem documentation

---

exercises/meetup/.meta/solutions/meetup.rb
exercises/meetup/meetup_test.rb

Test was supplying the 'date' library, but shouldn't.
Date requirement is now in the example solution.

Test no longer supplies the `date` dependency for solution

---

exercises/isogram/.meta/solutions/isogram.rb

#664 updated the `isogram` tests but not the example solution.
For some reason Travis CI, which would have detected this, did not run on that PR.
This patch updates the example solution to pass the updated tests.

isogram: update solution to pass current tests.

---

lib/generator.rb
lib/generator/command_line.rb
lib/generator/exercise.rb
lib/generator/files/generator_cases.rb
lib/generator/files/metadata_files.rb
lib/generator/files/track_files.rb
lib/generator/implementation.rb
lib/generator/template_values.rb
lib/generator/underscore.rb
test/fixtures/xruby/lib/generator/test_template.erb
test/generator/exercise_test.rb
test/generator/files/generate_cases_test.rb
test/generator/files/metadata_files_test.rb
test/generator/files/track_files_test.rb
test/generator/implementation_test.rb
test/generator/template_values_test.rb
test/generator/underscore_test.rb
test/generator_test.rb

In #641 - generator: refactor implementation, part 1, Hilary started some generator refactorings.  Progress on this seems to have stopped.
In order to continue the refactoring I have extracted from the uncontroversial changes from the initial PR. 
I have further built upon these changes to continue the refactoring. (To follow in further PRs.)

generator: refactor implementation, part 1 highlights.

---

lib/generator/command_line.rb
lib/generator/files/metadata_files.rb
lib/generator/files/track_files.rb
lib/generator/implementation.rb
lib/generator/repository.rb
lib/generator/template_values.rb
test/generator/files/metadata_files_test.rb
test/generator/files/track_files_test.rb
test/generator/implementation_test.rb
test/generator/repository_test.rb
test/generator/template_values_test.rb

Extract a `Repository` class that takes `paths` and `slug` as constructor arguments.
Repository in this case is an implementation of the Repository pattern which acts as an interface to all the data that an `Implementation` needs rather than anything related to Git repositories.
Continues the work done in #677, 
Supersedes  #643

generator: refactor implementation, part 2 - extract Repository

---

exercises/dominoes/.meta/generator/dominoes_case.rb
exercises/dominoes/dominoes_test.rb

Fixed the generator which broke when the expected value key was changed in the canonical data.
Regenerated test cases based on updated canonical data.
No change to the content of the tests so no BookKeeping::VERSION increment is required.

dominoes: Update generator and test cases

---

docs/EXERCISE_README_INSERT.md

Since the [removal of the shebang line](https://github.com/exercism/ruby/pull/685) tests are no longer directly executable, so remove the instructions about that from the Readme.

Remove instructions for direct test execution.

---

exercises/binary-search-tree/.meta/solutions/binary_search_tree.rb
exercises/binary-search-tree/binary_search_tree_test.rb

Check for VERSION on BookKeeping module in binary_search_tree

---

exercises/collatz-conjecture/.meta/generator/collatz_conjecture_case.rb
exercises/space-age/.meta/generator/space_age_case.rb
exercises/sum-of-multiples/.meta/generator/sum_of_multiples_case.rb
lib/generator/exercise_case.rb

refinements: removed from individual cases

---

config.json

The `blurb` is required by Nextercism to give a short overview of the language.
This text is taken from the front page of https://www.ruby-lang.org/en/

config.json: Add blurb, fix Gitter name

---

exercises/collatz-conjecture/.meta/generator/collatz_conjecture_case.rb
exercises/roman-numerals/.meta/solutions/roman_numerals.rb
lib/generator/underscore.rb

Ruby is/has deprecated the use of Fixnum, so we should as well.

Moving away from using Fixnum due to deprecation

---

exercises/hamming/.meta/generator/hamming_case.rb

The 'Hamming' canonical data has changed to return a hash when the
expected value is an error, rather than the integer value -1 that was
used previously.
Fixes #707

generator: hamming: Change error expectation to match json data.

---

exercises/bowling/bowling_test.rb

re: exercism/problem-specifications#832

Bowling: New descriptions from Canonical

---

exercises/space-age/.meta/generator/test_template.erb
lib/generator/template_values.rb
lib/generator/test_template.erb
test/generator/template_values_test.rb

The only place it is used is in the test template:
```
class <%= exercise_name_camel %>Test < Minitest::Test
```
Replace it with a new method `exercise_test_classname` that returns the
full expected classname without having to confuse the template user with
camels.
Closes #651

generator: Replace exercise_name_camel method

---

exercises/palindrome-products/README.md

This is a follow up PR for exercism/problem-specifications#897 and
exercism/ruby#723.  It is the application of the new README by using
`configlet generate . --only palindrome-products`

palindrome-products: Generate readme

---

exercises/simple-cipher/README.md

add missing 'd' to obscured string

simple-cypher: Fix typo

---

lib/generator/exercise_case.rb
lib/generator/underscore.rb
test/generator/exercise_case_test.rb

Remove unnecessary underscore in test method name to make it more readable
Issue: https://github.com/exercism/ruby/issues/668
Modify Underscore module to clean up leading/trailing whitespace
Updated `exercise_case_test.rb` to account for this case

generator: Remove underscore in test method name when canonical data has whitespace in description

---

README.md
lib/generator/command_line.rb
lib/generator/command_line/generator_optparser.rb
test/generator/command_line/generator_optparser_test.rb
test/generator/command_line_test.rb

fixes #631 
Replaces the --freeze and -f options with --update and -u.
Updates default --all behaviour to not update version.
Alternative implementation could involve *adding* an update option, instead of replacing the freeze option entirely.
`rake test:dev`

generator: replace --freeze with --update

---

exercises/queen-attack/.meta/generator/queen_attack_case.rb
exercises/queen-attack/queen_attack_test.rb

The queen-attack test generator is broken
Add proper logic to parse the position of the exercise.
* Ran `./bin/generate queen-attack`
Fixes #741
Add proper parsing logic for row, column coming from canonical data.

queen-attack: Update test generator

---

exercises/hamming/hamming_test.rb

Update hamming tests based on updated canonical data.
Change is minor so requires no BookKeeping version increment.

hamming: regenerate tests

---

docs/TESTS.md

Seems appropriate to link to the below section on disabling all skips, but I couldn't find examples of that happening elsewhere. Also not sure if tying the link in to github's style of id generation is desirable.
Edit: Add Github magic to auto-close issue.
Closes #753

documentation: Explain the point of skips. Closes #753

---

exercises/minesweeper/.meta/solutions/minesweeper.rb
exercises/minesweeper/minesweeper_test.rb

Fixing #778: Minesweeper test now listens for ArgumentError instead.

minesweeper: Change ValueError to ArgumentError

---

README.md

Wrote some documentation explaining how to regenerate test data and other data for exercises.  I also included some changes to explain when to use `-u` to update the VERSION number as well.  Lastly, I added a section to the *Contributing* section that gives some ideas for getting started to newcomers, including the newly revamped *Regenerating Test Suites* section.
Let me know what you think.  I'm happy to do some revising to get the wording just right.
Solves #717, as we discussed in that issue (see also some of the discussion in #757 PR.
No tests.  All I did was change the README.  However, the methodology that I wrote down is sound, because I just did it that way a couple of days ago 😄 
References #757 
Closes #717

documentation: Document test suite regeneration

---

Gemfile

I don't necessarily think this is particularly important, especially since the Gemfile is quite short, but I have been ordering my Gemfiles alphabetically for a while, and like the consistency of knowing where to look for things.

Order gems alphabetically in Gemfile

---

exercises/accumulate/.meta/hints.md
exercises/accumulate/README.md

Update the advanced section of the accumulate readme to ensure the
correct enumerator returns when no block is given.

Update accumulate, close #795

---

Gemfile
bin/generate
lib/generator.rb
lib/generator/command_line.rb
lib/generator/command_line/generator_optparser.rb
lib/generator/exercise_case.rb
lib/generator/files/metadata_files.rb
lib/generator/files/track_files.rb
lib/generator/implementation.rb
lib/generator/repository.rb
test/generator/case_values_test.rb
test/generator/command_line_test.rb
test/generator/files/metadata_files_test.rb
test/generator/files/track_files_test.rb
test/generator/implementation_test.rb
test/tasks/exercise_test.rb
test/tasks/exercise_test_tasks_test.rb
test/test_helper.rb

From require_all's changelog:
2.0.0:
Merged PR #24 (https://github.com/jarmo/require_all/pull/24) Prior to
version 2, RequireAll attempted to automatically resolve dependencies
between files, thus allowing them to be required in any order. Whilst
convenient, the approach used (of rescuing NameErrors and later retrying
files that failed to load) was fundamentally unsafe and can result in
incorrect behaviour (for example issue #8, plus more detail and
discussion in #21).
Thanks to Joe Horsnell (@joehorsnell)
This commit removes the dependency on the require_all gem by using
Ruby's `#require` method wherever it is needed.

800 Remove dependency on require_all

---

config.json

This is an attempt at setting up the Ruby track as a nextercism track.
As suggested in #815 I have cloned the Go tracks progression, removing exercises that are Go-specific, preserving Ruby-only exercises as bonus exercises.
After this changes the progression tree looks like this:
```
Ruby
====
core
----
├─ hello-world
│  └─ space-age
│
├─ two-fer
│  ├─ leap
│  ├─ triangle
│  └─ proverb
│
├─ hamming
│  ├─ rna-transcription
│  └─ nucleotide-count
│
├─ raindrops
│  ├─ accumulate
│  ├─ roman-numerals
│  └─ strain
│
├─ scrabble-score
│  ├─ etl
│  └─ protein-translation
│
├─ isogram
│  ├─ pangram
│  ├─ anagram
│  ├─ word-count
│  └─ run-length-encoding
│
├─ difference-of-squares
│  ├─ sum-of-multiples
│  ├─ pythagorean-triplet
│  ├─ largest-series-product
│  ├─ nth-prime
│  └─ isbn-verifier
│ …
```

Use progression from Go

---

config.json

This:
- makes Hello World unlock a few basic exercises, (by changing `'unlocked_by: null` to `hello-world`)
- make all other exercises currently `unlocked_by: null` move up one or two levels ( unlocked either by TwoFer or by Hamming).
In #518 the request was to restrict the number of `unlocked_by: null` to 4 or 5 exercises.
Am I right that `unlocked_by: hello-world` has the same effect in the track? I used that, to make it more explicit. 
This PR is an intermediate step in the Ruby Overhaul™.   
As a temporary step, all the other exercises that used_to be `unlocked_by: null` are now moved up 1 or 2 levels, so either by TwoFer for the lowest difficulties, or Hamming, for most others, and some with the highest difficulties quite arbitrary by later core exercises.
I also lowered the …

Change unlocking order step 1

---

README.md

BookKeeping section is no longer used in the exercise test cases. This PR removes the documentation in the readme.
Closes #838

Remove references to BookKeeping from readme

---

bin/generate
lib/generator/implementation.rb
test/generator/implementation_test.rb
test/test_helper.rb

When running `bin/generate --all` when a generator failed by raising an error it stopped the process. This change rescues the error, remembers the failure and continues on to the next generator.
At the end of the run a list of the broken generators is reported:
```
$ bin/generate --all
Generated affine-cipher tests version 1
...
Generated zipper tests version 71
Broken generators: (Run these individually to see the error raised.)
acronym
all-your-base
...
```
If a single generator is run the error will be raised and reported as normal:
```
$ bin/generate acronym
.../lib/generator/exercise_case.rb:27:in `method_missing': undefined local variable or method `phrase' for #<AcronymCase:0x00000000020edec0> (NameError)
...
```

generator: Report on broken generators

---

.travis.yml

Move Rubocop check after test run so that any failure message is visible
at the end of the log and not buried by all the test output.

travis config: Move Rubocop check after test run.

---

Rakefile
bin/generate
lib/generator/case_values.rb
test/generator/case_values_test.rb

Adds a Rubocop rake task.
It will run by default after the tests.
Also fix the things that Rubocop complained about.

Add Rubocop rake task

---

.gitignore
bin/generate

When running the bin/generator script, the name of the generator will be written to a `.last_generator_run` file.
This is useful for scripting and recovering from generator failures.
Add `.last_generator_run` to `.gitignore` because we don't want to check it in.

bin/generator: Write slug of last run generator to a file.

---

exercises/wordy/.meta/generator/wordy_case.rb
exercises/wordy/wordy_test.rb

Update `wordy` tests to: `1.2.0 86d0069`

wordy: Regenerate Tests

---

exercises/largest-series-product/.meta/generator/largest_series_product_case.rb
exercises/largest-series-product/largest_series_product_test.rb

Update `largest-series-product` tests to: `1.2.0 85da7a5`

largest-series-product: Regenerate Tests

---

exercises/ocr-numbers/.meta/generator/ocr_numbers_case.rb
exercises/ocr-numbers/ocr_numbers_test.rb

Update `ocr-numbers` tests to: `1.2.0 965ecad`

ocr-numbers: Regenerate Tests

---

exercises/queen-attack/.meta/generator/queen_attack_case.rb
exercises/queen-attack/queen_attack_test.rb

Update `queen-attack` tests to: `2.2.0 aaadbac`

queen-attack: Regenerate Tests

---

exercises/say/.meta/generator/say_case.rb
exercises/say/say_test.rb

Update `say` tests to: `1.2.0 a0cee46`

say: Regenerate Tests

---

config.json

This is one step in a process where I'm working on analyzing the exercises, in order to provide the best experience for both students and mentors. In the current order of the exercises, there's a gap between the very simple TwoFer exercise, and the next exercise Hamming, which is not so simple at all. So, I'm looking for exercises that bridge that gap, and also reordering the existing exercises. 
One question in the re-ordering is if adding extra core exercises would affect the queue and mentoring happiness. We're doing an experiment with another easy-to-mentor, early core exercise.
Acronym is our first choice, because:
- A _lot_ of the first submissions are very similar
- One snippet / precooked comment can cover 80% of new submissions, so it's supposed to be easy/fast to mentor
- It's a …

Ruby/Acronym : promote to core exercise

---

exercises/connect/.meta/generator/connect_case.rb
exercises/connect/connect_test.rb

README and test show test data as such for readability, test data should
should be passed in like the README indicates, without the spaces added
for readability.
Fixes #810 outstanding issue by striping out leading spaces in constructed board array.

connect: Strip leading whitespaces in test data.

---

config.json

... to check if Acronym's introduction to String#scan will change how many students will use `scan` in their first iteration in Word Count, and if that makes mentoring Word Count more interesting. 
Side effect: we're short one exercise being unlocked by TwoFer now that we take Word Count out.

Make Acronym unlock WordCount

---

exercises/accumulate/.meta/hints.md
exercises/accumulate/README.md

The ["Advanced" section of the accumulate README](https://github.com/exercism/ruby/blob/5f9efd80026a70bb881657c3f1d8281a19158db4/exercises/accumulate/README.md#advanced) suggests to return enumerator if no block was given. It provides an optional test for that.
However the test seems broken, since it expects `number * number` calculation being returned by `each`.
It should rather use `map` to return the result:
Reference: #796 #395

Accumulate: Fix additional enum test in readme

---

exercises/rail-fence-cipher/.meta/solutions/rail_fence_cipher.rb
exercises/rail-fence-cipher/rail_fence_cipher_test.rb

These Rubocop meta-comments are not required.

rail-fence-cipher: Remove Rubocop references

---

exercises/phone-number/.meta/generator/phone_number_case.rb
exercises/phone-number/.meta/solutions/phone_number.rb
exercises/phone-number/phone_number_test.rb

Update `phone-number` tests to: `1.6.0 a317aa4`
Update solution to pass updated tests.

phone-number: Regenerate Tests

---

config.json

I totally misunderstood how the arrangement of the core exercises worked, so I never put Acronym early in the track as intended in #874 .
With this PR, Acronym goes to the right place on the track, just after TwoFer. 
And while I was at it, I placed all the core exercises at the top of the file, for easy reference.
As I finally realized that there never have been a rearrangement in Exercism V2, I changed the sequence of the other core exercise where their position was really weird. 
For instance: Isogram is now an early exercise instead of one second to last.
Matrix has moved to an earlier position et cetera. 
To keep the changes readable:
No core exercises changed to side or the other way around; no changes in the unlocking of the exercises.  (The latter will follow in a new PR soon, …

Ruby/config Update core positions in track

---

exercises/change/.meta/generator/change_case.rb
exercises/change/.meta/solutions/change.rb
exercises/change/change_test.rb

Update `change` tests to: `1.3.0 258c807`
Update solution to pass updated tests.

change: Regenerate Tests

---

config.json
exercises/high-scores/.meta/generator/high_scores_case.rb
exercises/high-scores/.meta/hints.md
exercises/high-scores/.meta/solutions/high_scores.rb
exercises/high-scores/README.md
exercises/high-scores/high_scores_test.rb

This is part of the rearrangement of the track. 
One of the things missing is an easy exercise with an array as a list and some list manipulations.  
The Problem Specification PR is here:  https://github.com/exercism/problem-specifications/pull/1378
This High Scores exercise is meant to be a core exercise 
TwoFer -> Acronym ->  Isogram -> **High Scores**  -> Matrix -> ...
As we want to test drive, it's added here as a side exercise first. 
This exercise is also going to be the first core in the track where the students have to instantiate a class and work with multiple methods. We paid extra attention to the sequence of the tests, so the code is building up nicely, and at the end there should be some nice mentoring opportunities left.   
Thanks to @pgaspar, who took care of the …

New exercise: High Scores

---

exercises/grains/.meta/generator/grains_case.rb
exercises/grains/grains_test.rb

The grains canonical data changed, so update the generator to match.
There is no real change to the test file other than the version bump.

grains: Fix generator and regenerate tests

---

exercises/roman-numerals/.meta/solutions/roman_numerals.rb

Small refactor to pull the roman numerals into a constant since they will never change and don't need to live inside a method. If this were a running program it would also save a bit of memory since we wouldn't be instantiating a new hash every time the `ROMAN_MAPPINGS` are called

refactor: pull romans up into constant

---

config.json

In the process of the Great Ruby Overhaul, we're promoting High Scores to a core exercise. And moving Isogram a bit further in the track, because there are too many ways to solve it for it to be at the beginning of the track.

ruby: make High Scores core, move Isogram up

---

config.json

This is a next step in improving the unlocking of the side exercises.
Three goals for this step
- Make High Scores, as a new core exercise, unlock some sides
- Reduce the heap of sides unlocked by Hamming, and divide them more evenly
- Make the easiest exercises have really easy side exercises only
- I made it so that the last core exercises Tournament is the end of the track, and does not unlock any side exercises
Notes:

Redivide side exercises

---

config.json

In the last change, I made the last core exercise Tournament the end of the track. 
After consulting maintainers on Slack, the main feeling is that the last core should unlock side exercises as well. So I added some to be unlocked by Tournament again. 
The exercises I choose here are quite arbitrary. Feel very welcome to open a new PR if you feel the complexity of the exercises is not in sync with Tournament.

reset: make Tournaments unlock side exercises again

---

config.json

Next step in the Ruby Track Overhaul!  💎 
Most important updates:
- Promote Series to a core exercise
- Demote Robot Name to side exercise, because there are troubles with the tests, the instructions and what not. 
I like to do a promotion and demotion at the same time, to make it easier to redivide side exercises. 
Side effects:
I had to redivide the side exercises: 
- the ones unlocked by RobotName are now divided over other core exercises 
- Series needed a few side exercises, I stole them from other core exercises on roughly the same level
- And then I had to redivide some others, to balance the number of sides for each core. 
The changes for the side exercises are quite arbitrary, and will change all the time during upcoming changes. 
The changes to the core exercises are for real! 🎉 …

Make Series core, Robot Name side

---

exercises/ocr-numbers/.meta/hints.md
exercises/ocr-numbers/README.md

Regenerates the Readme file to include the new hints introduced on #901. Cleaned up some whitespace and moved the file to the correct directory first.
Resolves #913.

ocr-numbers: Regenerate README.md with new hints

---

exercises/series/.meta/hints.md
exercises/series/README.md

This separates the paragraph in Series' hints.md in two. Please see https://github.com/exercism/ruby/pull/916#issuecomment-456002645 for context.

series: Separate hints.md in two paragraphs

---

config.json

Another step in the Ruby Track Overhaul! 💎
* Most important updates:
- Promote Word Count to core: between Series and Hamming
- Demote Grains and Difference of Squares to side (due to a decision to [make all math exercises side exercises](https://github.com/exercism/exercism/issues/4110) in all tracks. This wasn't implemented in Ruby yet, because we had no substitutes ready.)
To make it easier to redivide side exercises, I combine promoting and demoting exercises at the same time. 
* Side effects: I had to redivide the side exercises.
- the ones unlocked by Grains and Difference of Squares are now divided over other core exercises
- Word Count needed a few side exercises, I stole them from other core exercises on roughly the same level
- And then I had to redivide some others, to balance …

Promote Word Count to core, demote math exercises

---

.rubocop.yml
.travis.yml
Gemfile
README.md

https://github.com/exercism/ruby/issues/930
I'd prefer to only upgrade ruby, but doing so breaks rubocop.
Upgrading rubocop on its own also isn't an option as it requires newer versions of ruby.
`./bin/compile --all`'s output doesn't change and the tests are passing.
Rubocop needed quite substantial changes. I'd be interested how the original .rubocop.yml was generated so that I can make my rubocop change less drastic.

Upgrade to ruby 2.5 and rubocop 0.63

---

exercises/high-scores/.meta/solutions/high_scores.rb
exercises/high-scores/README.md
exercises/high-scores/high_scores_test.rb

Update tests to: ~`3.0.0 999ec47`~ `4.0.0 ad1f9c4`
These are the changes introduced by:
* https://github.com/exercism/problem-specifications/pull/1447
* https://github.com/exercism/problem-specifications/pull/1459
Right now I kept the new method name `personal_top_three`, but a case could be made for naming it `personal_top_3` or rather `personal_top3`, as the [rubocop styleguide suggests](https://github.com/rubocop-hq/ruby-style-guide#snake-case-symbols-methods-vars-with-numbers). Personally, I'm not a fan of `personal_top3` 🤔 Thoughts are welcome.
@F3PiX I believe we can make this change without affecting the overhauling efforts, but let me know if that's not the case.
Also updated README.md :+1:

high-scores: Regenerate tests

---

exercises/beer-song/.meta/generator/beer_song_case.rb
exercises/beer-song/beer_song_test.rb
exercises/tournament/.meta/generator/tournament_case.rb
exercises/tournament/tournament_test.rb
exercises/transpose/.meta/generator/transpose_case.rb
exercises/transpose/transpose_test.rb
lib/generator/exercise_case/case_helpers.rb
test/generator/exercise_case/case_helpers_test.rb

Previously it used regular heredocs and removed the indentation using
regular expressions.
I think it is now easier to read and understand.
~A side-effect of this change is to upgrade the project to Ruby 2.3.
This is the version that introduced squiqqly heredocs.
I think it's reasonable to upgrade, as Ruby 2.3 first came out over 3
years ago (2015-12-25).~
Update: Ruby has been updated to 2.5 in #933

Use squiqqly heredoc in tests

---

exercises/acronym/.meta/generator/acronym_case.rb
exercises/acronym/acronym_test.rb
lib/generator/test_template.erb

We've [recently](https://github.com/exercism/ruby/pull/931#discussion_r251869850) stopped updating the Acronym exercise because of two new test cases:
* `test_apostrophes` (introduced by https://github.com/exercism/problem-specifications/pull/1377)
* `test_underscore_emphasis` (introduced by https://github.com/exercism/problem-specifications/pull/1436)
This PR changes the generator to automatically exclude these two test cases. With this change we can still get updates from the canonical version without adding the tests we don't want at the same time.
If the idea of excluding certain tests proves useful we may want to consider supporting it in the base `ExerciseCase` so it can be easily be used by other generators.

acronym: Update and exclude new tests

---

exercises/acronym/.meta/generator/acronym_case.rb
exercises/acronym/acronym_test.rb
lib/generator/test_template.erb

Reverts exercism/ruby#950
Reverts so that template changes can be made on it's own merits.

Revert "acronym: Update and exclude new tests"

---

lib/generator/test_template.erb

This change makes it possible for `ExerciseCase`s to override the `to_s` method, returning `nil` for tests we don't want for the Ruby track. You can see an example of this on #953.
Without this change these excluded tests would still not appear on the generated test file, but an extra new-line would be present where they would be, given how:
```ruby
[1, 2, nil, 4].join("\n")
[1, 2, nil, 4].compact.join("\n")
```
In practice, what this means is that, for example, on the Acronym update from #953 the generated test file `acronym_test.rb` will end with:
```ruby
end
end
```
Instead of:
```ruby
end
end
```
Note: #953 relies on this change.

[WIP] Handle test cases with to_s evaluating to nil

---

exercises/acronym/.meta/generator/acronym_case.rb
exercises/acronym/acronym_test.rb

Note: this PR was initially merged and reverted (#950). This new version separates the changes to the test template into its own PR (#952). This PR thus depends on PR #952.
We've [recently](https://github.com/exercism/ruby/pull/931#discussion_r251869850) stopped updating the Acronym exercise because of two new test cases:
* `test_apostrophes` (introduced by https://github.com/exercism/problem-specifications/pull/1377)
* `test_underscore_emphasis` (introduced by https://github.com/exercism/problem-specifications/pull/1436)
This PR changes the generator to automatically exclude these two test cases. With this change we can still get updates from the canonical version without adding the tests we don't want at the same time.
If the idea of excluding certain tests proves useful we may want to …

[WIP] acronym: Update and exclude new tests

---

config.json

- This is preparing for promoting ETL to a core exercise. As a core, ETL should go just after Word Count. Let's first check if, as a side,  it isn't too hard on this point in the track by making it unlocked by WordCount.   
- The difficulty score is arbitrary; the Track Anatomy Project didn't touch those yet. I just made it one step more difficult than WordCount.
@exercism/ruby

Move ETL close to WordCount

---

config.json
exercises/grep/.meta/generator/grep_case.rb
exercises/grep/.meta/generator/test_template.erb
exercises/grep/.meta/solutions/grep.rb
exercises/grep/README.md
exercises/grep/grep_test.rb

Closes #946.
The implementation was heavily influenced by [python's](https://github.com/exercism/python/blob/a83f53697a1a213967838a78b86f2b358727d76f/exercises/grep/example.py#L45). It can certainly be improved, but we may want to leave that for the mentor notes themselves, since the main goal here is to get CI to pass.
The tests are generated using the [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/grep/canonical-data.json), but the file contents are hardcoded in a custom test template. I ended up doing this because I couldn't easily pass custom variables from the test case file to the ERB test template. Without that I can't parse the canonical data comments and make the file contents dynamic, like some tracks do.
I couldn't find other exercises …

grep: New exercise

---

config.json

Resistor Color Duo was introduced in March, and added as a side exercise on [Level 1](https://github.com/exercism/ruby/issues/969) first.
As a core exercise, it brings in the `integer` datatype to level 1, and a simple array iterator (for beginners) or reading values from a hash. 
Looking at the [community solutions](https://exercism.io/tracks/ruby/exercises/resistor-color-duo/solutions), there's lots of opportunities to guide to more idiomatic Ruby.
(cc ~@exercism/track-maintainers~ Ruby maintainers)

Promote Resistor Color Duo to core

---

config.json

See #970
Resistor Color (#1 in the series) is added to the track as a side exercise, unlocked by Hello World.
The main reason to add the exercise was to have a replacement for Flatten Array. 
Flatten Array is not a nice exercise as an introduction to the track, because it's either just using the `Array#flatten` or reimplementing this built in method. 
Let's see if people have fun with if we move it to a later position, and if not, we can remove it from the track alltogether.
PS I changed the difficulty to 3, as a non-official way to reference the [level](#969). In the UI, it's still marked 'easy', AFAIK.

Move flatten array up in the track

---

config.json
exercises/transpose/.meta/generator/transpose_case.rb
exercises/transpose/transpose_test.rb
lib/generator/exercise_case/case_helpers.rb
test/generator/exercise_case/case_helpers_test.rb

Issue #949 indicates that it would be preferable to display the `input` and `expected` values as a single-line string rather than as a heredoc. 
From the issue:
input = "ABC\n123"
input = <<~INPUT.strip
ABC
123
INPUT
In this pull request, I have made the following changes:
- Create a new case_helper method that can take an array of strings and display with a separator defaulting to `"\n"`.
- Update `transpose_case.rb` so that it uses this `on_single_line` case helper where it previously used `indent_heredoc`.
- Generate updated test cases for `transpose_test.rb`.
All test cases still complete successfully after changes.
Please let me know if I can make any additional changes. Thanks!

Update transpose test case with new case_helper method.

---

config.json
exercises/armstrong-numbers/.meta/generator/armstrong_numbers_case.rb
exercises/armstrong-numbers/.meta/solutions/armstrong_numbers.rb
exercises/armstrong-numbers/README.md
exercises/armstrong-numbers/armstrong_numbers_test.rb

I have rebased the last ten commits of @Tuxified's work from #893 onto the current master.
[canonical-data.json](https://github.com/exercism/problem-specifications/blob/master/exercises/armstrong-numbers/canonical-data.json)

armstrong-numbers:  port

---

exercises/atbash-cipher/.meta/generator/atbash_cipher_case.rb
exercises/atbash-cipher/.meta/solutions/atbash_cipher.rb
exercises/atbash-cipher/atbash_cipher_test.rb

[canonical-data.json](https://github.com/exercism/problem-specifications/blob/master/exercises/atbash-cipher/canonical-data.json)
This exercise was only half implemented before, so I had to change the solution.
I regenerated the `README.md`, but there was no change.

atbash-cipher: implemented generator

---

exercises/high-scores/.meta/generator/high_scores_case.rb
exercises/high-scores/.meta/solutions/high_scores.rb
exercises/high-scores/high_scores_test.rb

https://github.com/exercism/problem-specifications/pull/1564 added a new method to high-scores: `latestIsPersonalBest`. This PR adds that method to our implementation and tests.

high-scores: Add latest_is_personal_best?

---

config.json
exercises/resistor-color-trio/.meta/generator/resistor_color_trio_case.rb
exercises/resistor-color-trio/.meta/solutions/resistor_color_trio.rb
exercises/resistor-color-trio/README.md
exercises/resistor-color-trio/resistor_color_trio_test.rb

Closes #979. I was waiting for https://github.com/exercism/problem-specifications/pull/1568 to be merged and didn't see the notification when it got merged a week ago. See the canonical data [here](https://github.com/exercism/problem-specifications/blob/master/exercises/resistor-color-trio/canonical-data.json).
The solution is based on code @F3PiX kindly gave me.
**TODO:**

resistor-color-trio: New exercise

---

exercises/prime-factors/.meta/solutions/prime_factors.rb
exercises/prime-factors/prime_factors_test.rb

`for` is a Ruby keyword, so this is just bad naming if you ask me.

PrimeFactors: Replace `for` with `of` (for is a Ruby keyword)

---

config.json

Trio seems to be too hard on its current position (start Level 2). So, not much fun to mentor, and struggling students.
As a side after HighScores, the gap is too big. In HighScores, the design of the class is forced by the tests. In Trio, a lots of decisions to make at once.

Move Resistor Trio up in the track

---

exercises/resistor-color-trio/README.md

As pointed out in https://github.com/exercism/ruby/pull/995#commitcomment-35058392 by @brunohq, #995 introduced a duplicate sentence in Resistor Color Trio's readme. Please refer to that PR for more context.

resistor-color-trio: Remove duplicate Readme sentence

---

exercises/twelve-days/twelve_days_test.rb

Closes #1005. I figured this wording is better, and it should make the button to update the exercise visible.

Delete unnecessary instructions in Twelve Days test

---

exercises/binary-search/.meta/generator/binary_search_case.rb
exercises/binary-search/.meta/solutions/binary_search.rb
exercises/binary-search/binary_search_test.rb

- Add missing generator to `binary-search` as per #396.
- Fixes `binary_search.rb` according to canonical tests.

Binary search generator

---

exercises/bob/bob_test.rb

re: exercism/problem-specifications#1630

Update Bob for language changes

---

exercises/linked-list/linked_list_test.rb

I noticed that the last two tests were not skipped for whatever reason

Skip all but first test by default for linked-list

---

exercises/microwave/.meta/solutions/microwave.rb
exercises/microwave/microwave_test.rb

If I enter a nonzero number of minutes into my microwave and add a
number of seconds that exceeds 1 minute, the correct behaviour would be
to add the additional minute to the existing minutes already input.
To test this, add the input `272`, which first is understood as 2
minutes 72 seconds, and then the 72 seconds is understood as 1 minute 12
seconds. The result is 3 minutes 12 seconds.
As noted in the README, this microwave *does* convert the input to
canonical format before display, so the output we would want here is
03:12.
The repo's solution was required to be changed to pass this new test.
Before its change, it had the result of "02:72" which violates the
README's stipulation that the microwave converts to canonical.

microwave: Test that minute overflow adds to input minutes

---

exercises/matrix/matrix_test.rb

While mentoring the exercise of one of the mentee https://exercism.io/mentor/solutions/8f836f0ff9264cea98b3d2c45d010a8a I found the mentee has implemented `columns` and tried to make the test pass as:
```ruby
def columns
return_array = []
(rows.length - 1).times do |num|
return_array << rows.map { |row| row[num] }
end
return_array
end
```
And, now since we had only a test case to extract the 2nd column, the above implementation seems to be passing.
Adding the test case to check the last column as well.

matrix: add testcase for last column

---

docs/LEARNING.md

The course material is no longer available on our former platform, classes link has been (temporarily) suspended for RubyLearning.  Regular content is available, and of course, I am still available for answers in regard to the RubyLearning.com site.

RubyLearning .org domain not set up for classes

---

config.json

Ruby's examples live inside a solutions subdir, not at the apex of .meta.

Fix example filepath in track's config.json

---

exercises/concept/amusement-park-improvements/.meta/config.json
exercises/concept/amusement-park/.meta/config.json
exercises/concept/assembly-line/.meta/config.json
exercises/concept/bird-count/.meta/config.json
exercises/concept/boutique-inventory-improvements/.meta/config.json
exercises/concept/boutique-inventory/.meta/config.json
exercises/concept/lasagna/.meta/config.json
exercises/concept/log-line-parser/.meta/config.json
exercises/concept/moviegoer/.meta/config.json
exercises/concept/savings-account/.meta/config.json
exercises/concept/simple-calculator/.meta/config.json

The authors and contributors of exercises are stored in an array of objects in the exercises' `.meta/config.json` files.
Each author/contributor used to have two properties: their GitHub username _and_ their Exercism username.
As we're only using the GitHub username, we're flattening the `authors` and `contributors` array to an array of strings representing the GitHub usernames.
We will update `configlet` to validate the new structure, so you might be seeing build failures once we've implemented this change. 
See https://github.com/exercism/docs/pull/90/files
We will automatically merge this PR immediately to be able to submit a different PR in which we'll add the authors/contributors for practice exercises.
https://github.com/exercism/v3-launch/issues/26

🤖 Flatten authors and contributors in .meta/config.json files

---

concepts/arrays/.meta/config.json
concepts/basics/.meta/config.json
concepts/blocks/.meta/config.json
concepts/booleans/.meta/config.json
concepts/classes/.meta/config.json
concepts/conditionals/.meta/config.json
concepts/floating-point-numbers/.meta/config.json
concepts/instance-variables/.meta/config.json
concepts/loops/.meta/config.json
concepts/nil/.meta/config.json
concepts/numbers/.meta/config.json
concepts/ostruct/.meta/config.json
concepts/strings/.meta/config.json
config.json

_TL;DR; Add authors/contributors to a new `concepts/<slug>/.meta/config.json` to Concepts in the same way you have for Concept Exercises._
---
To properly attribute authorship/contributorship for an individual concept, each concept will have its own `.meta/config.json` file with `authors` and `contributors` keys like those for concept and practice exercises. We're also moving the concept's blurb from the track's `config.json` to the `.meta/config.json` file, also similar to concept and practice exercises.
See https://github.com/exercism/docs/pull/96/files for the update to the specification.
This PR adds a `.meta/config.json` file for all concepts found in the track's `config.json` file containing:
- A `blurb` key, which value is copied from the `config.json` file and subsequently removed …

🤖 Add .meta/config.json file for concepts

---

concepts/advanced-enumeration/introduction.md

Enumerable#find returns the first matching element, not an array containing the first matching element.
Source: https://apidock.com/ruby/Enumerable/find

Minor correction in introduction.md

---

exercises/concept/savings-account/savings_account_test.rb

Set the delta as tight as possible, but allow for float approximations when performing float calculations in the exercises (i.e. `1_016.21` vs `1_016.20999999`). Still use `assert_equal` when methods should return
specific floats.
This addresses #1199.

Use `assert_in_delta` when testing float values

---

exercises/concept/assembly-line/assembly_line_test.rb

With this push request we avoid failing tests in submissions that use a slightly different order of arguments in the tested method, which causes a small difference in the calculated result.
I set the the delta to a values that makes sense for the problem being solved.
This pull requests is created following https://github.com/exercism/ruby/pull/1201, which covers the same issue for a different exercise.

Assembly Line: Use assert_in_delta when comparing float values

---

README.md

Update reference of "Master in README to "main".
Details regarding this rename can be found here:
https://github.com/github/renaming

Update references of "master" in README to "main"

---

exercises/concept/savings-account/savings_account_test.rb

This is a duplication of #1190.  It has been a few weeks since the original post, and over a week since the last comment was posted.  I ran across this same issue today while working on this exercise.  It appears that the typos have been fixed on the main branch already, so I just included the number fixes (i.e. making the test honest about testing a negative balance).

Savings-Account: Fix copy/paste error from positive to negative test.

---

exercises/concept/savings-account/savings_account_test.rb

As discussed briefly in slack, start using `assert_in_delta` consistently when comparing floats.

Use assert in delta throughout

---

exercises/practice/zipper/zipper_test.rb

Adds a test to the Zipper exercise to check that the zipper can go deep in the structure and return to the top.
The issue within problem-specifications is here: https://github.com/exercism/problem-specifications/issues/1872
Addresses https://github.com/exercism/ruby/issues/1260

Zipper test to check go deep and return

---

exercises/practice/palindrome-products/.meta/example_2.rb

This example_2 is ~~about 60%~~ more than two times faster than the present one.
* It still uses a double loop on `@range` because `repeated_combination(2)` is waaay slower.
* ~~`r1 * r2 if r2 >= r1` prevents to calculate `2*1` when we already have `1*2` mimicking `repeated_combination`~~ Redefined the range instead.
* It is much more efficient to recalculate the factors afterwards than to store them during the loops where it creates a lot of unnecessary `Palindrome` objects (or even only arrays of `[product, [i, j].sort]`).
* And the way they are calculated prevents `palindrome.factors << [i, j].sort; palindrome.factors.uniq!` just with `div <= number`.
* `n == n.to_s.reverse.to_i` is ~15% faster than `n.to_s == n.to_s.reverse`.
* Finally I found that adding a method `palindrome?` or …

Proposed new example for Palindrome Products

---

exercises/concept/simple-calculator/.docs/instructions.md

Update instructions typo, part 2 is meant to test unsupported operation vs invalid string argument.
Might cause confusion with beginners who have the sequencing of their error handling around the wrong way to start.

simple-calculator: fix instructions typo in part 2

---

exercises/concept/moviegoer/moviegoer.rb

The `attr_reader :age, :member` line is not necessary since we don't need to expose the attributes.

Moviegoer: remove unnecessary "attr_reader"

---

exercises/concept/log-line-parser/.docs/introduction.md

https://ruby-doc.org/core-2.7.0/String.html#method-i-capitalize-21
Based on the ruby docs, the `capitalize!` method should result in this: 
```
my_string.capitalize!  #=> "Hello"
puts my_string         #=> "Hello"
```
`nil` happens if the string is already capitalized. The full capitalization of the entire string is the `upcase` method.

log-line-parser: Fix readme for `capitalize!` method

---

docs/LEARNING.md

The link goes to the wayback machine, for now.
Hopefully I can recover the domain record.  But if not, then the changes
will need to be made permanent, perhaps the resource moved to another
domain.
I am trying to communicate with the new registered entity to resolve
this.

Link to wayback machine for rubylearning.com

---

exercises/practice/food-chain/food_chain_test.rb

Using HereDoc removes the artificial block and line continuation, and
gives a nicer terminal view of the message, rather than breaking words
at arbitrary places in a terminal that is fairly standard width.

Use HereDoc for NoCheating exception message

---

exercises/practice/book-store/.meta/config.json
exercises/practice/book-store/.meta/example.rb
exercises/practice/book-store/book_store_test.rb

Changes in example.rb:
- fixed hardcoding problem
- reduced the 3 main blocks of loops to 2
- improved code readability (I think...) while using approx. 40% fewer lines (~~29~~ 26 instead of 46)
- removed private method, changed each element of GROUP_DISCOUNTS constant to 1 - old value, and put the equation that was in the aforementioned method into groups.sum{...}, thus replacing groups.map{...}.inject(0,:+)
~~Changes in book_store_test.rb:~~
~~- changed numbers to words in function definitions (for consistency's sake)~~
~~- added test_group_of_one_and_four_is_cheaper_than_group_of_two_and_three~~
Changes in config.json:
- added my handle as a contributor

[book-store]: Rewrote example.rb

---

exercises/concept/boutique-inventory/.docs/instructions.md
exercises/concept/boutique-inventory/.meta/exemplar.rb
exercises/concept/boutique-inventory/boutique_inventory_test.rb

fixes: #1315
* addresses rubocops in the files touched
* updated the [instructions.md](./exercises/concept/boutique-inventory/.docs/instructions.md) to remove ambiguity about stock levels
* updated tests to reflect that stock levels do not impact `item_name` determination

fix: `BoutiqueInventory#item_name` assertions

---

exercises/practice/protein-translation/.meta/example.rb

The class was not private, since `private` only effects the methods at
the `instance` level.
Includes the following changes:
- Detach methods from class definition
- remove redundant _key part of variable name
- No need for `.nil?` check explicitly
- Make class method private

protein translation private class method

---

exercises/practice/all-your-base/.meta/example.rb

The `private_class_method` directive needs a list of method names (strings
are converted to symbols for that list) in order to make the methods
private.  It does not work the same as the familiar `private` method
used at the instance level.
This change creates meta-class instance methods as a group and applies
the familiar `private` directive to the methods that follow that
directive.

Make the desired class methods private

---

exercises/practice/series/.meta/tests.toml

This explicitly skips the test case for 'way too large' since in Ruby there's no practical difference between 'too large' and 'way too large'.

Sync series exercise with problem specifications

---

.rubocop.yml

In pull request #1356 we added some top-level
exclusions, and removed some explicit rubocop
disable directives.
I forgot to check that the disabled directives
all were redundant, and ended up removing a couple that weren't covered by the top-level exclusion.
Since we don't care too hard about the ABC metric
for tests, this adds an additional top-level
exclusion that covers these tests.

Add an exclusion for rubocop ABC metric

---

exercises/practice/bowling/.meta/config.json
exercises/practice/bowling/.meta/tests.toml
exercises/practice/bowling/bowling_test.rb

This syncs the metadata and tests.toml with the changes in problem-specifications.
It also regenerates the tests based on tests.toml.

Update bowling from problem-specifications

---

exercises/practice/allergies/.docs/instructions.md
exercises/practice/allergies/.meta/tests.toml
exercises/practice/allergies/allergies_test.rb

This syncs the docs as well as the test list (tests.toml) with the data from problem-specifications, adding one missing test.
I regenerated the test suite from scratch, making individual tests instead of grouping them as we did before. It looks like the choice to group the tests was based on a previous version of the canonical data, and that we didn't have a strong philosophical preference for doing it that way.
I added custom messages to the asserts and refutes (per #386), and am happy to tweak those if anyone has any suggestion for improvements there.

Update allergies to match problem-specifications

---

exercises/practice/pangram/.docs/instructions.md
exercises/practice/pangram/.meta/tests.toml
exercises/practice/pangram/pangram_test.rb

The sync only brought over one reimplemented test, but when regenerating the test suite I got several changes to both test names and data.
My guess is that we synced the tests.toml previously without updating the test suite.
I did not use single quotes when regenerating.
We don't take a hard stance on this with Rubocop, so I'm choosing to just go with what is easiest.

Sync pangram with problem-specifications

---

exercises/practice/anagram/.docs/instructions.md
exercises/practice/anagram/.meta/tests.toml
exercises/practice/anagram/anagram_test.rb

This sync applied some reimplemented exercises that changed the data being used.
Two notes on the choices I made:
1. I generated this with double quotes rather than single quotes. We do not have the Rubocop StringLiterals enabled, so I could not autocorrect to use single quotes. I personally don't think it makes a difference, but thought I should call it out.
2. I explicitly did not call the 'sort' method on the values returned. Our reference implementation still passes, but it does mean that we're changing the design of the exercise to no longer require that people return the values in sorted order, but rather to return them in the order that the candidates were passed in. I think this makes more sense, but it could break some people's earlier solutions.

Sync anagram with problem-specifications

---

.rubocop.yml
exercises/practice/protein-translation/protein_translation_test.rb

Rubocop is an internal tool, and should not be exposed to students.
If they wish to apply rubocop rules to their own code, then it should be up to them to install rubocop and add their own preferred configuration.
This removes one last rubocop disable directive from an exercise test suite, adding an explicit configuration for the rule (which is a reasonable rule), and explicitly disabling the rule for the test suite that violates it intentionally.
I believe that our current Rubocop setup is now good enough for our needs, and that we can close #443.
I imagine that we may run into a few more things we will want to change, but I think it's worth opening an issue to discuss for individual questions that arise rather than trying to do a big overhaul all at once.

Remove rubocop directive in user-facing test suite

---

exercises/practice/book-store/.meta/config.json

jdr implemented book-store in #762.
This is the last exercise that was missing authors in the .meta/config.json.
Closes #1067

Give credit to author of book-store exercise

---

exercises/practice/series/.meta/example.rb
exercises/practice/series/series_test.rb

The tests in the test suite did not correspond to the tests in the tests.toml file.
This regenerates the test suite to match.
Note that the sample implementation was failing after this change, as there were new error cases that the reference solution wasn't handling.
I made the minimum change necessary to get the reference solution passing.
After making this change I ran `bin/configlet sync --update --exercise series` and configlet said that everything is fine.

Regenerate series based on tests.toml

---

exercises/practice/meetup/meetup_test.rb

The test data matched, but the test names did not, so they got updated.
After regenerating I ran `bin/configlet sync --update --exercise meetup`, and configlet says everything is up to date.

Regenerate meetup tests based on tests.toml

---

exercises/practice/two-bucket/.docs/instructions.md
exercises/practice/two-bucket/.meta/tests.toml
exercises/practice/two-bucket/two_bucket_test.rb

When syncing the tests.toml there were three possible new tests. Two of them added error handling, which I decided to exclude, as I don't think error handling makes this exercise more interesting.
Regenerating changed from single quotes to double quotes, which I think is fine, since we haven't taken a strong stance on that from the Rubocop perspective.

Sync two-bucket with problem-specifications

---

exercises/practice/roman-numerals/.docs/instructions.md
exercises/practice/roman-numerals/.meta/tests.toml
exercises/practice/roman-numerals/roman_numerals_test.rb

This added a few new tests.
When I regenerated the single quotes were replaced with double-quotes, which seems fine.

Sync roman-numerals with problem-specifications

---

config.json

This is a scripted change.
Since `configlet fmt` doesn't yet operate on the track config, I went ahead and did a Ruby `JSON.pretty_generate` on it in the first commit so that the second will be easy to verify.
The topics entry is deprecated. We kept it around in order to be able to populate the practices and prerequisites fields.
Since practices and prerequisites now have values, the topics can be deleted.

Delete deprecated topics from track config

---

exercises/practice/scrabble-score/scrabble_score_test.rb

The metadata and docs were already synced, but the test suite did not reflect the data in tests.toml.
This regenerates the test suite per the selected data.
Note that this removes the much-discussed test for nil input.
Closes #1002

Sync scrabble-score with problem-specifications

---

exercises/practice/flatten-array/.docs/instructions.md
exercises/practice/flatten-array/.meta/config.json
exercises/practice/flatten-array/.meta/tests.toml
exercises/practice/flatten-array/flatten_array_test.rb

Syncing brought in new docs, metadata, and tests to the tests.toml.
I chose to exclude tests for "null-like" values, as Ruby only has nil and these are already thoroughly tested.
When regenerating the tests I inlined the variable for tests where asserting that the result is an empty array.

Sync flatten-array with problem-specifications

---

exercises/practice/gigasecond/.docs/instructions.md
exercises/practice/gigasecond/.meta/tests.toml

I chose to not bring in the new test for immutable datetimes, as the DateTime and Time classes in Ruby create new copies of themselves when making changes to them, as far as I can tell.

Sync gigasecond with problem-specifications

---

config.json

We have implemented list-ops, which encompasses both strain and accumulate.
Therefore, to keep the track more interesting this deprecates both of the smaller exercises, removing the overlap.

Deprecate strain and accumulate

---

exercises/practice/crypto-square/.meta/tests.toml
exercises/practice/crypto-square/crypto_square_test.rb

Regenerating the test suite added a new test.
As before, it also replaced single quotes with double quotes.

Sync crypto-square with problem-specifications

---

config.json
exercise-concepts.todo.json

The track-level config.json maps concepts to the exercises that teach them and practice them.
As part of preparing for the v3 release we added concepts to all the practice exercises' practices and prerequisites arrays. However, since many of these concepts have not yet been taught, configlet is complaining about a mismatch.
This moves any unimplemented concepts out of the data for the practice exercises and into a separate JSON file.
That will let us write a script in the future to move concepts back as we implement them.
Closes #1218

Store future concepts in separate config

---

exercises/practice/high-scores/.docs/instructions.md
exercises/practice/high-scores/.meta/config.json
exercises/practice/high-scores/.meta/tests.toml
exercises/practice/high-scores/high_scores_test.rb

There were a slew of new tests for methods that were not previously a part of the API of the class.
None of the methods are mentioned in the instructions for the exercise, and they also don't seem very interesting, so I didn't bring them in.
When regenerating the test suite the test for the #latest_is_personal_best? method got removed, so I removed the corresponding code from the reference solution as well.

Sync high-scores with problem-specifications

---

exercises/practice/book-store/.docs/instructions.md
exercises/practice/book-store/.meta/tests.toml
exercises/practice/book-store/book_store_test.rb

The sync updated the docs and the tests.toml file.
Regenerating the test suite added several new tests. One of the tests had a failure due to a rounding difference:
Expected: 145.6
Actual: 145.60000000000002
I changed the test suite to use assert_in_delta instead.

Sync book-store with problem-specifications

---

exercises/practice/accumulate/.meta/tests.toml

The accumulate exercise is deprecated, but configlet is warning that it is outdated, so I decided to sync it and exclude all the new tests so that it will be excluded from future linting.
Configlet has an open issue about not linting these (exercism/configlet#518).

Sync accumulate with problem-specifications

---

exercises/practice/scale-generator/.docs/instructions.md
exercises/practice/scale-generator/.meta/config.json
exercises/practice/scale-generator/.meta/example.rb
exercises/practice/scale-generator/.meta/tests.toml
exercises/practice/scale-generator/scale_generator_test.rb

This is a major overhaul of the exercise.
I did it in three steps, first removing a requirement that didn't add anything to the exercise, then changing the design of the expected solution to have a clearer separation between the base chromatic scale and the requested scale based on intervals.
Finally, syncing with the problem-specifications pulled down a major overhaul of the description and reimplemented most of the tests, due to the last character in the `pattern` having previously been ignored, which was very confusing for people.

Sync scale-generator with problem-specifications

---

exercises/practice/tournament/.docs/instructions.md
exercises/practice/tournament/.meta/example.rb
exercises/practice/tournament/.meta/tests.toml
exercises/practice/tournament/tournament_test.rb

The sync brought in changes to the docs and tests.toml
The example solution failed the new test due to a small formatting difference in the spec. The new test is the first one that shows a score that has double-digits.
I updated the example solution to pass the new test, but did not spend any time thinking about how to make the code nice.

Sync tournament with problem-specifications

---

exercises/practice/armstrong-numbers/.meta/config.json
exercises/practice/book-store/.meta/config.json
exercises/practice/change/.meta/config.json
exercises/practice/complex-numbers/.meta/config.json
exercises/practice/dominoes/.meta/config.json
exercises/practice/high-scores/.meta/config.json
exercises/practice/isbn-verifier/.meta/config.json
exercises/practice/isogram/.meta/config.json
exercises/practice/poker/.meta/config.json
exercises/practice/resistor-color-duo/.meta/config.json
exercises/practice/tournament/.meta/config.json
exercises/practice/transpose/.meta/config.json

In the past three weeks I've gone through most of the practice exercises, updating them according to changes in the problem-specifications repository.
For some exercises there were only docs/metadata changes. I've not added myself as a contributor to these.
I've only added myself to exercises that required updating the test suite.

Add kytrinyx as contributor to updated exercises

---

exercises/practice/high-scores/.meta/tests.toml
exercises/practice/high-scores/high_scores_test.rb

When I was originally updating this exercise from problem-specifications
I misunderstood the meaning of the test cases that have properties named
`*After*`. I completely missed that these were tagged with the
`immutable` scenario.
These are not actual properties, but named scenarios that
describe expectations around immutability.
I have now implemented these test cases, since the Ruby implementation
would allow students to create an implementation that mutates
internal state in a way that would break the expectations around
`.latest` and `personal_best`.

Add immutibility test cases for high-scores

---

exercises/practice/two-fer/two_fer.rb

The `ruby/two-fer/README.md` file says nothing about TDD. I recommend we either remove this (as I've done in this PR) or provide updated instructions if there are docs on TDD elsewhere. Thanks!

Remove erroneous instructions

---

exercises/concept/amusement-park/.docs/instructions.md

The amusement-park exercise has incorrect numbering and repeats the 4th instruction as an instruction number when it should be 5 instead.

Update documentation to fix numbering issue.

---

.github/workflows/exercise-tests.yml

From the Official Ruby Learning website:
https://www.ruby-lang.org/en/downloads/branches/
Ruby 2.6
status: eol
release date: 2018-12-25
EOL date: 2022-04-12

Ruby 2.6 is almost one year past EOL

---

exercises/concept/assembly-line/.docs/introduction.md

A floating point number has at least one number after the decimal point, not zero or more.
This explanation conflicts with the integers explanation which states its "numbers with no digits behind the decimal separator".

Update explanation of floating point numbers for Ruby Assembly Line exercise

---

exercises/practice/pythagorean-triplet/.meta/example.rb
exercises/practice/pythagorean-triplet/pythagorean_triplet_test.rb

The pythagorean-triplet exercise wasn't following the spec
even a little bit.
This rewrites the test suite to follow the existing
canonical data, and rewrites the solution to make it
pass.
The last test takes a long time to run, which isn't ideal but I couldn't find a way around it without going all mathlete on it.
See discussion here: https://forum.exercism.org/t/the-ruby-pythagorean-triplet-exercise-has-something-wrong-with-it-1497/4259/6

Rewrite pythagorean-triplet

---

exercises/practice/acronym/.meta/tests.toml

The tests.toml file had two tests that were not included in the test suite.
This has been the case since before v3, as far as I can tell.

Fix acronym tests.toml

---

exercises/practice/hello-world/hello_world_test.rb

Minitest version 5.0.0 was released in May 2013.
That's 10 years ago. We don't need to worry about this anymore.

Don't catch load error in hello-world

---

exercises/practice/minesweeper/.meta/example.rb
exercises/practice/minesweeper/minesweeper.rb
exercises/practice/minesweeper/minesweeper_test.rb

This exercise was originally implemented before the shared spec was created.
This reimplements the exercise per the spec.
Note that the `tests.toml` (incorrectly) had all of these tests marked as being included, so no changes to the test metadata were necessary.
The biggest changes are:
- The class name is now `Minesweeper` (instead of `Board`), and the property under test is `annotate` (instead of `transform`).
- There is no error handling
- The board no longer has edges, just the cells.
This will break all existing solutions, but I think that it's worth it, in order to bring this in line with the shared canonical data.

Reimplement minesweeper

---

exercises/practice/gigasecond/.meta/tests.toml
exercises/practice/gigasecond/gigasecond_test.rb

The gigasecond second is fully specified with only the two test
cases that pass in a fully qualified time.
Let's get rid of the other test cases.

Remove redundant tests in gigasecond

---

exercises/practice/saddle-points/.docs/instructions.md
exercises/practice/saddle-points/.docs/introduction.md
exercises/practice/saddle-points/.meta/example.rb
exercises/practice/saddle-points/saddle_points_test.rb

This changes the test suite to follow the canonical spec,
and updates the example implementation to match.
The original version of this exercise was implemented before
the shared specs were a thing, and it has therefore not
benefited from the improvements that have been made to the
inputs and outputs over the years.
This will break all existing solutions.
Note that this also brings in a tweak to the instructions.

Reimplement saddle-points

---

exercises/practice/perfect-numbers/.meta/tests.toml

The tests.toml file was inconsistent with the
test suite for this exercise.
This removes entries for unimplemented tests.

Normalize perfect-numbers tests.toml

---

exercises/practice/palindrome-products/.meta/tests.toml

The tests.toml file was inconsistent with the
test suite for this exercise.
This removes entries for unimplemented tests.

Normalize palindrome-products tests.toml

---

exercises/practice/gigasecond/gigasecond_test.rb

I forgot to do this in the previous PR where I deleted
the unnecessary tests.

Unskip first test in gigasecond

---

exercises/practice/resistor-color-trio/.meta/example.rb
exercises/practice/resistor-color-trio/resistor_color_trio_test.rb

I don't think error handling adds anything interesting
to the exercise, so I've deleted the test for it.
This brings the exercise in line with the data in the
problem-specifications.
Note that there are unimplemented tests upstream, which
this doesn't address.
This doesn't break existing solutions.

Normalize resistor-color-trio exercise

---

exercises/practice/matrix/.meta/example.rb
exercises/practice/matrix/matrix_test.rb

The tests.toml for matrix didn't correspond
to the implementation at all.
This implements all the tests per the spec
and the tests.toml.
This also changes the expected implementation
to match the expectations described in the
canonical data.
The Ruby implementation was accessing the underlying
rows/columns directly using the zero-based index, whereas
the spec works with the more human-readable 1-based
row number and column number.
Note that this breaks all existing solutions.
I think that it is worth it, in order to be able to use the canonical data.

Tweak matrix implementation

---

exercises/concept/port-palermo/.docs/instructions.md
exercises/concept/port-palermo/.meta/config.json
exercises/concept/port-palermo/.meta/exemplar.rb
exercises/concept/port-palermo/port_palermo.rb
exercises/concept/port-palermo/port_palermo_test.rb

This PR fixes the rubocop issue of the [Constant Name](https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Naming/ConstantName) for the exercise concept of port-palermo. Since usage of uppercase constants are recommended by the rubocop docs and it is a good practice.
This PR is the new version of [the previous one](https://github.com/egemen-dev/ruby/tree/port_palermo_constant_fix). I mistakenly deleted the previous one with the forked repo so, I had to open a new one.

Fix rubocop error for the constant by converting to uppercase - new

---

exercises/concept/port-palermo/.meta/exemplar.rb

This PR removes a redundant 'return' statement

[Port Of Palermo] Remove redundant returns in exemplar

---

exercises/concept/amusement-park/.docs/hints.md

Change duplicate hint number 4 to hint number 5.
Instead of duplicate hints number : 
4. Allow people to buy a pass
4. Revoke the pass
This should be hints number :
4. Allow people to buy a pass
5. Revoke the pass
Maybe it will show up the hint number '5. Revoke the pass' too, as it doesn't show up yet with the screenshot below !

Fix duplicate hints number

---

exercises/concept/boutique-inventory/.docs/introduction.md

Add the missing question mark (?) to method all. 
Instead of method `all`, it should be method `all?` (with the question mark)

Fix typo in method name

---

exercises/concept/chess-game/.docs/hints.md
exercises/concept/chess-game/.docs/instructions.md
exercises/concept/chess-game/.docs/introduction.md

- Also fixes trailing white space in hints file.

Integer is class in Ruby

---

exercises/concept/locomotive-engineer/.docs/introduction.md

Improve syntax error output on array decomposition :
- on `(a, b), (d) = fruits_vegetables` decomposition, add a new syntax error output
- on `((a, b), (d)) = fruits_vegetables` decomposition, move the syntax error output below
For two decomposition, having two distinct syntax errors outputs are more clear rather than having only one syntax error output.

Improve syntax error output

---

exercises/concept/chess-game/.docs/introduction.md

("aa".."az").to_a # => ["aa", "ab", "ac", ..., "az"] 
"aa".."az".to_a # => Error: undefined method `to_a' for "az":String (NoMethodError)

Corrected parentheses usage in range creation

---

concepts/basics/about.md
concepts/multiple-assignment-and-decomposition/about.md
concepts/multiple-assignment-and-decomposition/introduction.md
concepts/ranges/about.md
concepts/ranges/introduction.md
exercises/concept/chess-game/.docs/introduction.md
exercises/concept/locomotive-engineer/.docs/instructions.md
exercises/concept/locomotive-engineer/.docs/introduction.md

In line with Exercism's spec, we're ensuring that all admonition fences are demarcated with four tildes (`~~~~`) across all repositories. We will be following up with an org-wide script that can be used to keep this consistent. [Problem Specifications](https://github.com/exercism/problem-specifications) has already been updated.
We'll automatically merge this a week from now, but feel free to merge beforehand!
- Spec: https://exercism.org/docs/building/markdown/markdown#h-special-blocks-sometimes-called-admonitions
- Meta issue: https://github.com/exercism/exercism/issues/6705

Convert backtick (`) admonition fences to tildes (~)

---

.rubocop.yml
config.json
exercises/practice/gilded-rose/.docs/hints.md
exercises/practice/gilded-rose/.docs/instructions.md
exercises/practice/gilded-rose/.meta/config.json
exercises/practice/gilded-rose/.meta/design.md
exercises/practice/gilded-rose/.meta/example.rb
exercises/practice/gilded-rose/gilded_rose.rb
exercises/practice/gilded-rose/gilded_rose_test.rb

https://forum.exercism.org/t/add-the-gilded-rose-kata/7758
This version is a bit different from the classic Gilded Rose Kata. See https://github.com/exercism/ruby/commit/1094e5373d737a300b2609e024cb5e7441a37803 for the changes of substance _(EDIT: simplified, [see discussion below](https://github.com/exercism/ruby/pull/1586#discussion_r1364528806))_, and https://github.com/exercism/ruby/commit/6d034738d87437a2c279b2482946d5d4e2c5ab25 for the rationale. Feedback on this adjustment is welcome!
I've also edited the instructions from the original for clarity, conciseness, and emphasis on the task of refactoring.
~~### Note on the linter warnings~~
~~All of the warnings are about the starting code (which is _supposed_ to be horrible), except for one, an "Ambiguous negative number operator" …

[New practice exercise] Gilded Rose

---

config.json
exercises/practice/gilded-rose/.meta/config.json

Adds to `config.json` for the new Gilded Rose exercise:
- Contributors list
- Reviewers of #1586 plus BethanyG, who gave extensive feedback in the [forum thread].
- Minimum Ruby version of 3.1
- The tests use omitted values in hash literals, a Ruby 3.1 feature.
- ~~In the root `config.json`, removes the prerequisites for Gilded Rose. This makes the exercise more easily accessible to Ruby devs who aren't already on Exercism. (If they came for Gilded Rose, did the "Hello world" exercise, and then saw that they still needed to other exercises first, they might give up.)~~
- _EDIT: Removed, see blow._
I also wanted to specify an `icon`, but [the existing icons](https://exercism.org/docs/building/tracks/icons#h-exercise-icons) are specific to other exercises, and googling didn't turn up any …

Update config for Gilded Rose exercise

---

exercises/practice/gilded-rose/.docs/instructions.md

Forum post where this was proposed: http://forum.exercism.org/t/add-the-gilded-rose-kata/7758/14
This adds a line to to instructions to clarify that students don't need to check for invalid starting values.

Clarify Gilded Rose exercise instructions re: invalid input values

---

exercises/concept/chess-game/.docs/introduction.md

"Hello World"[..5] should evaluate to "Hello " to include the space at the end since the range is inclusive.

Add space in chess-game's README

---

concepts/conditionals/.meta/config.json
concepts/conditionals/about.md
concepts/conditionals/introduction.md
concepts/conditionals/links.json
exercises/concept/assembly-line/.docs/introduction.md

The aim is to clean up the docs from mentions of integers, and also to expand on the concept.

[Refactor Concept]: conditionals 

---

.github/workflows/exercise-tests.yml

This PR updates GitHub Actions workflows to a specific version.
This ensures that the workflow will always run the same code, which makes your build _stable_.
It will also prevent a potential security issue where a tag could be replaced by a malicious commit without consumers being aware of it.
The PR updates each non-SHA based workflow reference with the SHA of the referenced version/tag, so the current behavior should not change.
See https://exercism.org/docs/building/github/gha-best-practices#h-pin-actions-to-shas for more information.

CI: pin GitHub Actions workflows

---

exercises/concept/blackjack/blackjack_test.rb

The function call `Blackjack.first_turn("ace", "king", "none")` in the test `test_first_turn_blackjack_with_nine_for_dealer` is supposed to take "nine" as the third argument instead of "none" as it is stated in the test name itself.

Fix typo in BlackJack problem for Ruby

---

config.json

Aligns this variable with the truth of this repo.
(see https://github.com/exercism/ruby/pull/1623#issuecomment-1910595560)

Fix wrong example path in config.json

---

config.json
exercises/practice/dnd-character/.docs/instructions.md
exercises/practice/dnd-character/.meta/config.json
exercises/practice/dnd-character/.meta/example.rb
exercises/practice/dnd-character/.meta/tests.toml
exercises/practice/dnd-character/dnd_character.rb
exercises/practice/dnd-character/dnd_character_test.rb

Add `dnd_character` exercise based on 48in24 implementation status page: https://exercism.org/challenges/48in24/implementation_status
And on the forums: https://forum.exercism.org/t/add-dnd-character-exercise/9492

Add dnd_character exercise

---

config.json
exercises/practice/spiral-matrix/.docs/instructions.md
exercises/practice/spiral-matrix/.meta/config.json
exercises/practice/spiral-matrix/.meta/example.rb
exercises/practice/spiral-matrix/.meta/tests.toml
exercises/practice/spiral-matrix/spiral_matrix.rb
exercises/practice/spiral-matrix/spiral_matrix_test.rb

Forum thread: https://forum.exercism.org/t/add-spiral-matrix-exercise/9795
Ran into some issues with Rubocop's ABC complexity for generating the matrix, as well as it being unhappy with using `attr_reader` in some cases so would be interested in feedback for the example solution, but don't need it to be a blocker for getting the code in!

Add spiral matrix exercise

---

concepts/multiple-assignment-and-decomposition/about.md
exercises/concept/locomotive-engineer/.docs/instructions.md
exercises/concept/locomotive-engineer/.docs/introduction.md
exercises/concept/locomotive-engineer/locomotive_engineer_test.rb

exercises/concept/locomotive-engineer/locomotive_engineer_test.rb
- Corrected typo in the name of "Leipzig" (×2)
- Add line-break for legibility in 1 test method
- [no important files changed]
exercises/concept/locomotive-engineer/.docs/introduction.md
- "keywword" → "keyword"
exercises/concept/locomotive-engineer/.docs/instructions.md
- "a array" → "an array"

Typo in Locomotive Engineer

---

exercises/practice/knapsack/.docs/hints.md

This PR places the hints for Knapsack under a "General" heading.
In the recently-implemented Knapsack exercise, only the last section in `hints.md` is being displayed in the editor UI. See the screenshot below.
It seems that a single `General` heading is expected for practice exercises, and if it doesn't exist, the contents under the last heading are used and the previous sections are omitted, as in this case.

Fix Knapsack `hints.md` headings

---

config.json
exercises/practice/zebra-puzzle/.docs/instructions.md
exercises/practice/zebra-puzzle/.meta/config.json
exercises/practice/zebra-puzzle/.meta/example.rb
exercises/practice/zebra-puzzle/.meta/tests.toml
exercises/practice/zebra-puzzle/zebra_puzzle.rb
exercises/practice/zebra-puzzle/zebra_puzzle_test.rb

Forum thread: https://forum.exercism.org/t/add-zebra-puzzle-exercise-48in24/10368
Note that I've disabled a RuboCop rule in part of the example solution. LMK if that's something we should avoid.

Add Zebra Puzzle exercise

---

exercises/concept/chess-game/.docs/instructions.md

There was an extra `}` in one of the examples in the exercise instructions.  This MR removes it.

[Chess Game] Fix typo in instructions

---

exercises/practice/knapsack/.docs/hints.md
exercises/practice/knapsack/.meta/example.rb

After recently implementing Knapsack (#1644), I realized that there's a much simpler brute-force approach that is still performant with the small input sets that are in the tests.
This PR:
- Adds hints on this brute-force approach as a starting point.
- Replaces the example solution, just to add variety to the example solutions across different tracks. (The existing example solution is based directly on the C++ version.)

Add easier hint and example solution for Knapsack exercise

---

exercises/concept/bird-count/bird_count_test.rb
exercises/concept/lasagna/lasagna_test.rb
exercises/concept/log-line-parser/log_line_parser_test.rb
exercises/practice/rail-fence-cipher/rail_fence_cipher_test.rb
exercises/practice/raindrops/.meta/example.rb
exercises/practice/roman-numerals/.meta/example.rb
exercises/practice/run-length-encoding/.meta/example.rb
exercises/practice/say/.meta/example.rb

The changes remove the magic comment for frozen strings, but also makes
mutable strings were necessary to avoid unnecessary test failures for
students.

Changes for upcoming default frozen strings

---

config.json
exercises/practice/eliuds-eggs/.docs/instructions.md
exercises/practice/eliuds-eggs/.docs/introduction.md
exercises/practice/eliuds-eggs/.meta/config.json
exercises/practice/eliuds-eggs/.meta/example.rb
exercises/practice/eliuds-eggs/.meta/tests.toml
exercises/practice/eliuds-eggs/eliuds_eggs.rb
exercises/practice/eliuds-eggs/eliuds_eggs_test.rb

This adds Eliud's Eggs exercise, as I mentioned in https://forum.exercism.org/t/add-eliuds-eggs-exercise-48in24/11252.
Please let me know anything I did wrong since this is my first time contributing to Exercism.

Add Eliud's Eggs exercise

---

concepts/symbols/about.md
concepts/symbols/introduction.md

Changes made in: https://github.com/exercism/ruby/pull/1607 weren't applied to the concept docs

Sync symbol concept docs to be the same as its exercise

---

exercises/practice/dnd-character/dnd_character_test.rb

maintainer, this could be x:rep/tiny

Adding missing skips to dnd-character exercise

---

exercises/practice/bank-account/bank_account_test.rb

This does not break any tests, but will correct backward communication.

For tests, expected comes before actual

---

exercises/concept/assembly-line/.docs/introduction.md

Please see the forum
http://forum.exercism.org/t/misinfo-in-ruby-concept-exercise/12633/2

fix introduction.md in 'assembly-line' exercise

---

exercises/practice/series/.meta/example.rb
exercises/practice/series/series_test.rb

This test now raises if the series is 0 instead of of the slice slice
size being larger than the series.
This allows one to raise on normalization of user input, the series
given, rather than incidentally having the slice size of 1 be larger
than the series size from a zero length string.
The example solution is updated to raise specifically for a zero length
series, rather than the incidental raising when slices are asked for.

Series: Test is not testing for zero length series

---

Gemfile
Gemfile.lock
bin/rubocop-quick

- Rubocop changed auto-correct to autocorrect
- base64 will be dropped from stdlib in Ruby 3.4

Address deprecations

---

exercises/practice/leap/.docs/instructions.append.md

The discussion in #1532 called for appending the instructions for leap to instruct the user not to use the Date class in Ruby.
Discussion on forums is:  [Append Ruby leap instructions to instruct user not use Date class](https://forum.exercism.org/t/append-ruby-leap-instructions-to-instruct-user-not-use-date-class/17515).

Append leap instructions to instruct user not use Ruby Date class

---

exercises/concept/assembly-line/.docs/introduction.md

The documentation specifies a list of comparisons that will return `true`, but has `5 < 4`, which is `false`. This swaps the values to provide the correct comparison.

[Assembly Line] Fix incorrect `<` comparison

---

bin/generate
generatorv2/lib/generator.rb
generatorv2/lib/utils.rb
generatorv2/test/utils_test.rb

The fix for the exercise name was only applied for the generator not the bin script. The underscore method in the generator will now clear all characters which is not numbers or letters. Noticed this would conflict when a description on problem spec had for example "," in it. Further, are there some formatting changes to make so it formats the files correctly.

Fix exercise naming in generator

---

bin/generate
generatorv2/lib/generator.rb
generatorv2/lib/utils.rb
generatorv2/test/utils_test.rb

* Enhance underscore method to filter invalid characters and update test file naming convention
* Add test case which test underscore for special characters
* Use character classes in regex. Also expose description for nested test cases.
* Underscore must not create multiple underscores around special characters

Fix exercise naming in generator (#1770)

---

exercises/concept/boutique-inventory/.docs/introduction.md
exercises/concept/boutique-inventory/boutique_inventory_test.rb

The typos in the Boutique Inventory documentation and test files have been corrected.
Please review.
Reference:
- [Boutique Inventory](https://exercism.org/tracks/ruby/exercises/boutique-inventory)
- [Exercism Community Topics（Fix typo in BoutiqueInventory）](https://forum.exercism.org/t/fix-typo-in-boutiqueinventory/19037)

Fix typo in boutique inventory

---

exercises/concept/bird-count/bird_count_test.rb

BirdCountTestTwo typos in method names within the file have been corrected.
Please review.
Reference:
- [Bird Count](https://exercism.org/tracks/ruby/exercises/bird-count)
- [Exercism Community Topics（Fix typo in BirdCount）](https://forum.exercism.org/t/fix-typo-in-birdcount/19036)

Fix typo in bird_count_test.rb

---

exercises/concept/moviegoer/.docs/hints.md
exercises/concept/moviegoer/.docs/instructions.md

Typos in the Moviegoer documentation file have been corrected.
Please review.
Reference:
- [Moviegoer](https://exercism.org/tracks/ruby/exercises/moviegoer)
- [Exercism Community Topics（Fix typo in Moviegoer HINTS.md）](https://forum.exercism.org/t/fix-typo-in-moviegoer-hints-md/19038)

Fix typo in moviegoer

---

bin/generate
exercises/practice/atbash-cipher/.meta/test_template.erb

When the script threw an error, it would rescue it. Now it doesn't do that; instead, it instantly fails.

Fix verification script 

---

exercises/concept/chess-game/.docs/instructions.md
exercises/concept/chess-game/.meta/exemplar.rb
exercises/concept/chess-game/chess_game.rb
exercises/concept/chess-game/chess_game_test.rb

The [problem description](https://exercism.org/tracks/ruby/exercises/chess-game#:~:text=3.%20Get%20player%27s,as%20capitalized%20string) uses `nickname`, but the exercise code defined `nick_name`.
This update renames the method to `nickname` for consistency between the description and the code.
Please review. 
[Exercism Community Topics（Rename nick_name method to nickname for consistency）](https://forum.exercism.org/t/rename-nick-name-method-to-nickname-for-consistency/19034)

Chess Game: Rename nick_name method to nickname for consistency

---

exercises/practice/grade-school/.meta/test_template.erb
exercises/practice/grade-school/grade_school_test.rb
exercises/practice/hamming/.meta/test_template.erb
exercises/practice/hamming/hamming_test.rb
exercises/practice/house/.meta/example.rb
exercises/practice/house/.meta/test_template.erb
exercises/practice/house/house_test.rb
exercises/practice/isbn-verifier/.meta/test_template.erb
exercises/practice/isbn-verifier/isbn_verifier_test.rb
exercises/practice/isogram/.meta/test_template.erb
exercises/practice/isogram/isogram_test.rb
exercises/practice/kindergarten-garden/.meta/test_template.erb
exercises/practice/kindergarten-garden/kindergarten_garden_test.rb

Includes:
- Grade school
- Hamming
- House
- Isbn verifier
- Isogram
- Kingergraten garden
NOTE:
House have got breaking changes and the exercise is changed to match the way it is presented in problem spec.

Add templates for exercises batch 5

---

exercises/practice/perfect-numbers/.meta/config.json
exercises/practice/perfect-numbers/.meta/example.rb
exercises/practice/perfect-numbers/.meta/test_template.erb
exercises/practice/perfect-numbers/perfect_numbers_test.rb

The intention was to add missing test cases. Added a test template to be used with the new generator in the process.
Discussion: https://forum.exercism.org/t/added-missing-test-cases-and-a-test-template-for-perfect-numbers/19262

Add test template for perfect-numbers

---

exercises/practice/roman-numerals/.meta/test_template.erb
exercises/practice/roman-numerals/roman_numerals_test.rb
exercises/practice/rotational-cipher/.meta/test_template.erb
exercises/practice/rotational-cipher/rotational_cipher_test.rb
exercises/practice/run-length-encoding/.meta/test_template.erb
exercises/practice/run-length-encoding/run_length_encoding_test.rb
exercises/practice/saddle-points/.meta/test_template.erb
exercises/practice/say/.meta/test_template.erb
exercises/practice/say/say_test.rb
exercises/practice/scrabble-score/.meta/test_template.erb
exercises/practice/scrabble-score/scrabble_score_test.rb
exercises/practice/secret-handshake/.meta/test_template.erb
exercises/practice/secret-handshake/secret_handshake_test.rb

Includes:
- Roman numerals
- Rotational cipher
- Run length encoding
- Saddle points
- Say
- Scrabble score
- Secret handshake

Add templates for exercises batch 10
