gigasecond/gigasecond_test.rb

I had some problems when doing the exercice because of the DST. I think more explicit method's name should help.
Thanks

Change test names to be easier to understand

---

twelve-days/twelve_days_test.rb

Missing value for expected variable in verse 8

Missing value for expected variable in verse 8

---

kindergarten-garden/kindergarten_garden_test.rb

Skipping setup for later tests so that user only needs to deal with one test at a time.

Skipping setup for later tests

---

acronym/acronym_test.rb
acronym/example.rb
config.json

I had an idea for a problem: shorten a string to its acronym. Like Portable Network Graphics :arrow_right: PNG.
I wrote tests and an example solution in Ruby. I don't know where a README should go, but I'm submitting this so you can review the idea.

Added acronym problem

---

luhn/luhn_test.rb

it's a little more descriptive

use refute rather than "assert !"

---

phone-number/phone_number_test.rb

make sure they're not just always chopping off the 1

Area codes can have the 1 in them

---

sum-of-multiples/sum_of_multiples_test.rb

Adding test cases to Sum of Multiples as per exercism/exercism.io#2341.

Add test cases to Sum of Multiples

---

gigasecond/example_gen.rb
gigasecond/gigasecond_test.rb

side effects:
- 1 additional test method
- the naming of the test methods has changed

gigasecond: added example generator and updated the tests

---

config.json
hello-world/example.rb
hello-world/hello_world_test.rb

This addresses exercism/rossconf#2 towards goal [#12](exercism/rossconf#12).
The hello-world exercise has three test cases, one for no name given, one for the name 'Alice' given and one for the name 'Bob' given. This is to avoid the hardcoding of a name into the solution.

Add introductory hello-world exercise

---

hamming/example.rb
hamming/example_gen.rb
hamming/hamming_test.rb

hamming exercise:
- added an example generator
- regenerated the tests with it

Hamming generate tests

---

hello-world/example.rb
hello-world/hello_world_test.rb

A follow up to my comments in PR #120

Default name of 'world' solves the no name case

---

bob/bob_test.rb
crypto-square/crypto_square_test.rb
custom-set/custom_set_test.rb
etl/etl_test.rb
food-chain/food_chain_test.rb
gigasecond/example_gen.rb
gigasecond/gigasecond_test.rb
grade-school/grade_school_test.rb
hamming/hamming_test.rb
nth-prime/nth_prime_test.rb
ocr-numbers/ocr_numbers_test.rb
rna-transcription/rna_transcription_test.rb
robot-name/robot_name_test.rb
simple-linked-list/simple_linked_list_test.rb
strain/strain_test.rb

Updated styles to match.
Related but not reliant on 3802a76297c5 commit.

Style Guide adherence

---

twelve-days/example.rb
twelve-days/song.txt
twelve-days/twelve_days_test.rb

This takes the same approach as food-chain, reducing the required API to a single
module-level or class-level method, and moving the lyrics into a static file.
It provides a single acceptance test, as well as a book-keeping test ("VERSION", so that people know which version of the test suite people are solving against).
Coincidentally, this fixes style violations ('long line') in the test suite.

Simplify twelve-days

---

bin/local-status-check
bin/setup-git-hoooks

They are one and the same file, but used automatically or manually.
This does not link the file... but does a physical copy to `.git/hooks`.
solves #159

Pre-Push and local check setup.

---

README.md

re: #56
This relies on PR #161

Notes for git hooks for Problem Authors

---

Makefile

Clean up temporary files created for tests

---

SETUP.md

Add 'ruler' and some formatting

---

scrabble-score/scrabble_score_test.rb

Uses a legal length word

---

README.md

The terms problems and test suites were being used interchangeably, which confuses new contributors. Have corrected this to be clearer about what is being referred to, either problems or test suites.

Cleaned up references to problems and test-suites

---

grade-school/example.rb
grade-school/grade_school_test.rb

Changed grade-school problem to use `#to_h` instead of `#to_hash`.

Grade school patch

---

gigasecond/example.tt

I''ve only included the generator template on the understanding the the test generation would be run to crate the new set of tests. I I should include the other affected files, please let me know (.version, example.rb and gigasecond_tests.rb).

Included messages in test generator

---

difference-of-squares/difference_of_squares_test.rb
difference-of-squares/example.tt

Corrected typo in version comments

---

protein-translation/example.rb
protein-translation/protein_translation_test.rb

Cystine is something else. Minor, but I am a protein scientist and care about such things.

Fixes "Cysteine" typo

---

difference-of-squares/difference_of_squares_test.rb

Spelling correction in version test comment for difference_of_squares exercism.

Correct typo in version comment

---

sum-of-multiples/sum_of_multiples_test.rb

add missing test to sum-of-multiples exercise

---

.rubocop.yml
.travis.yml
Gemfile
bin/local-status-check
exercises/acronym/acronym_test.rb
exercises/binary-search-tree/binary_search_tree_test.rb
exercises/etl/etl_test.rb
exercises/grade-school/grade_school_test.rb
exercises/leap/leap_test.rb
exercises/nth-prime/nth_prime_test.rb
exercises/robot-name/robot_name_test.rb
exercises/simple-linked-list/simple_linked_list_test.rb
exercises/strain/strain_test.rb

Made corrections for deprecated file patterns and style cops

Deprecated cops, deprecated file patterns

---

exercises/beer-song/beer_song_test.rb
exercises/beer-song/example.rb

The final beer-song test was not actually testing anything.
This is much more straight-forward, asserting that the entire song's
output matches the expected lyrics.

improve beer song API and tests

---

exercises/simple-linked-list/example.rb

Unused and unasked for to_s removed

---

SETUP.md

Fix link for installation and learning resources

---

exercises/nth-prime/nth_prime_test.rb
exercises/robot-name/robot_name_test.rb

Time to start thinking about Ruby 2.3

Freeze constant heredoc or use magic comment

---

exercises/say/say_test.rb

related https://github.com/exercism/xruby/pull/259 Thanks @kotp

Add missing skips

---

exercises/scrabble-score/scrabble_score_test.rb

Use a uppercased word to test case insensitivity
fixes #272

Scrabble Score case insensitive

---

.gitignore

Editor and Operating System related files are not "Project" related.

Ignore only the projects ignored files

---

Makefile
README.md

ASSIGNMENT and ARGS documented, showing how to run a single test, and
how to activate pride, as one possible argument to minitest.

Add color option in tests

---

config.json
exercises/perfect-numbers/example.rb
exercises/perfect-numbers/perfect_numbers_test.rb

Will be working on translating to ruby

add perfect-numbers

---

config.json

This is tied to exercism/exercism.io#2893

Config for Gitter Room Chat on page

---

docs/RESOURCES.md

RubyMonk is a go to resource for learning Ruby!

Added Ruby Monk

---

lib/bookkeeping.md

Suggest adding BookKeeping near end of the file

---

lib/generator.rb

Now gives a helpful error message if you run a test generator without
already having the x-common repository set up in the correct location.
(Also: Extracted methods from generate to appease Rubocop.)

Generator: Add message if x-common doesnt exist.

---

exercises/grade-school/example.rb
exercises/grade-school/grade_school_test.rb

The `School` object is now only tested via its public query methods `grades` and `students_by_grade`

Grade school: Make tests less implemetation dependent.

---

config.json
exercises/rail-fence-cipher/example.rb
exercises/rail-fence-cipher/rail_fence_cipher_test.rb

I'm working on tests and a reference solution for the rail-fence-cipher exercise.

add rail-fence-cipher

---

docs/RESOURCES.md

Added Learn Ruby the Hard Way and Codecademy

Added learning resources

---

config.json

The list-ops exercise was merged from an abandoned pull request that
appeared to be mostly ready.
Since I am not 100% sure it is ready, I'm moving it to the end of the
problem list. Once it has been solved a few times we can look at moving
it to a more appropriate position.

Move list-ops to the end.

---

config.json

Revert "Move list-ops to the end."

---

config.json

The list-ops exercise was merged from an abandoned pull request that
appeared to be mostly ready.
Since I am not 100% sure it is ready, I'm moving it to the end of the
problem list. Once it has been solved a few times we can look at moving
it to a more appropriate position.

Move list-ops to the end of the problem list.

---

config.json
exercises/diamond/diamond_test.rb
exercises/diamond/example.rb

Add diamond

---

config.json
exercises/all-your-base/all_your_base_test.rb
exercises/all-your-base/example.rb

I'll will be working on this exercise.

[WIP] add all-your-base

---

README.md

a step in fixing https://github.com/exercism/exercism.io/issues/3112.

attribute the vienna.rb icon Floor Dress(?) let us use

---

lib/generator.rb

Use new x-common directory structure

Update ruby generator

---

.rubocop.yml

Disabled Rubocops, all available listed in config

---

exercises/accumulate/accumulate_test.rb
exercises/accumulate/example.rb

I'm not sure if this would be the first version of the tests, so if anyone knows differently please let me know and I can edit it.

accumulate: add bookkeeping

---

exercises/bob/bob_test.rb
exercises/bob/example.rb

Can be solved using a module, then you can import Bob's personality in
any given object.
The object being used in the test itself was driving implementation
detail, unnecessarily.

bob: Opens up conversation about implementation choice

---

docs/24pullrequests.md

Still has some work to do.  Please let me know what we need.  This 24PullRequests has started a few hours ago...
@kytrinyx Anything you can think of?

Raw Brainstorming Version of 24 Pull Requests Ruby

---

Rakefile

When commit this, I realize the git hooks did not attempt to test these.

Add description for default task for rake -T

---

exercises/series/example.rb
exercises/series/series_test.rb

Previous test looked for arrays of Ints but exercise prompt in readme called for strings.  This update makes tests look for strings.

series: series_test.rb test for strings not arrays

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE
.github/PULL_REQUEST_TEMPLATE.md

This will provide a template for when folks open an issue or pull request.
This is based on the generator as introduced at [GitHub Issue and Pull Request Templates: Choose Your Own Adventure](https://wptavern.com/github-issue-and-pull-request-templates-choose-your-own-adventure) blog.

Templates for Issues and Pull Requests

---

README.md

travis-ci build status badge

---

.github/PULL_REQUEST_TEMPLATE.md

I've used the PR template quite a bit at this point. I found the template helpful, especially at first. 
@kotp asked me to take a pass through it and make any suggestions I might have to improve it.

documentation: update pull request template

---

exercises/phone-number/.meta/generator/phone_number_cases.rb

This adds a generator for phone-number and generates test cases based on the latest version of the canonical-data.json from x-common.
Depends on: https://github.com/exercism/xruby/pull/594, https://github.com/exercism/xruby/pull/596

phone-number: Add test generator.

---

README.md

`example.rb` has to stay where it is, pending changes to `configlet`

generator: remove premature update to README

---

exercises/dominoes/dominoes_test.rb

Regnerate tests based on updated canonical data.

dominoes: Update tests.

---

README.md

We missed updating the README in the process of sorting out the needed changes to configlet, etc.

generator: update location of example solution in README

---

lib/generator/command_line.rb
lib/generator/command_line/generator_optparser.rb

I started work on adding the `--all` option and quickly realized that `command_line.rb` needed some love. So I decided to take a step back and do the refactor in the current version of `command_line.rb` (with the current tests, etc) in a separate PR.
I have not yet made changes to the existing tests. I'd like to get some feedback before proceeding.

generator: separate option parsing from generator class construction

---

test/test_helper.rb

Update the way simplecov groups the files so that everything appears in the correct tab of the code coverage report.

meta: Update simplecov configuration.

---

lib/generator/files/generator_cases.rb
lib/generator/template_values.rb
test/generator/files/generate_cases_test.rb

A series of refactoring steps on  `lib/generator/files/generator_cases.rb` and it's tests.
See commit messages for details.

Refactor generator cases

---

README.md
lib/generator/command_line.rb
lib/generator/command_line/generator_optparser.rb
lib/generator/files.rb
lib/generator/files/generator_cases.rb
lib/generator/files/metadata_files.rb
lib/generator/files/track_files.rb
lib/generator/repository.rb
lib/generator/template_values.rb
lib/tasks/exercise.rb
test/generator/command_line/generator_optparser_test.rb
test/generator/files/generate_cases_test.rb
test/generator/files/metadata_files_test.rb
test/generator/files/track_files_test.rb
test/generator/files_test.rb
test/generator/repository_test.rb
test/generator/template_values_test.rb
test/tasks/exercise_test.rb

A refactor for exercism/xruby#624
I didn't realize quite how much of a mess this was until I started working on it. Good call, @Insti.
We have a couple of gaps in our test coverage, despite the 100% metric. (Look at the commit history and comments to see what I mean).
I pushed through to finishing the PR rather than figure out how to test the gaps because I'm not sure that writing those tests is the best answer. I think there's another refactor lurking that would obviate the need for the tests...

generator: slugs everywhere [closes #624]

---

sed

deletes a noise file that slipped in in exercism/xruby#632

deleted errant file

---

lib/generator/files/generator_cases.rb

a small refactor extracted from exercism/xruby#633 so it doesn't get lost.

generator: use file methods to manipulate filenames :)

---

lib/generator.rb
lib/generator/command_line.rb
lib/generator/implementation.rb
test/generator/implementation_test.rb

in prep for splitting out third model

generator: rename Exercise to Implementation

---

lib/generator/exercise_case.rb
lib/generator/exercise_case/assertion.rb
lib/generator/exercise_case/case_helpers.rb
lib/generator/template_values.rb
test/generator/exercise_case/case_helpers_test.rb

These refactorings are not directly relevant to separating the canonical data methods from ExerciseCase so I've separated them from the changes required for #648

Hilary's ExerciseCase refactorings

---

README.md

Because some PR's come in to only add book keeping version information, we should let folks know this comes in to play once the exercise tests are generated.
closes #671

BookKeeping VERSION as it relates to Generated Exercises

---

exercises/hamming/RUNNING_TESTS.md
exercises/hello-world/GETTING_STARTED.md

+ Edit GETTING_STARTED.md to remove references to multiple tests since
there is only one test in the suite.
+ Add RUNNING_TESTS.md, which includes instructions for running multiple
tests.
closes #681

hello-world/hamming: Separate GETTING_STARTED and RUNNING_TESTS instructions.

---

README.md
lib/generator/command_line/generator_optparser.rb
lib/helper.rb
test/generator/command_line/generator_optparser_test.rb
test/generator/command_line_test.rb

x-common to problem-specifications name

---

docs/ABOUT.md

Includes other considerations from issue exercism/meta#85 discussion.

Single sentence lines

---

exercises/flatten-array/README.md

Fix null to nil since it is appropriate as Ruby code.

Fix example code

---

exercises/hamming/hamming_test.rb

BookKeeping version NOT updated, due to the canonical data changes not
changing the meaning of any of the tests.
They were just a minor re-ordering.

hamming: Regenerate tests.

---

exercises/all-your-base/all_your_base_test.rb

Reference exercism/problem-specifications#830

All Your Base: Update test case ordering

---

exercises/rna-transcription/rna_transcription_test.rb

re: problem-specifications#838

RNA Transcription: Correct abbreviations in user-facing descriptions

---

exercises/hello-world/GETTING_STARTED.md

Small change in capitalization and punctuation on lines 98-99.
Solves [issue 3618](https://github.com/exercism/exercism.io/issues/3618)
- [ x ] Bug fix (non-breaking change which fixes an issue)
- [ x ] Gardening (code and/or documentation cleanup)
References #3618 on repo exercism.io
- [ x ] I have read the **CONTRIBUTING** document.

Fixed typos in GETTING_STARTED.md (issue #3618)

---

exercises/leap/leap_test.rb

Regenerate tests based on updated canonical data.
No BookKeeping version increment:
Minor test value change, Any solutions that passed the previous version of the tests should also pass this version.

leap: regenerate tests

---

exercises/isogram/isogram_test.rb

Regenerate tests based on updated canonical data.
No BookKeeping version increment:
Minor test value change, Any solutions that passed the previous version of the tests should also pass this version.

isogram: regenerate tests

---

exercises/secret-handshake/README.md

Fix link in README as per [exercism/problem-specifications/pull/1029](https://github.com/exercism/problem-specifications/pull/1029)

secret-handshake: fix link in README.md

---

exercises/change/README.md

change: generate readme.md

---

README.md

documentation: Update Readmes instructions

---

exercises/rotational-cipher/README.md

rotational-cipher: Generate readme.md

---

exercises/accumulate/README.md

accumulate: Regenerate readme

---

README.md

Adds the desired generator and minimal or partial solution that we want for new exercise pull requests.

README.md: some guidelines for implementing a new exercise

---

docs/24pullrequests.md

Content was moved in exercism/exercism.io#3526

Getting involved in a track

---

exercises/hamming/RUNNING_TESTS.md

A test suite will never have 0 assertions, and so I replaced line 39 to say that there were 16 assertions process opposed to 0.

Fix incorrect documentation

---

config.json
config/maintainers.json

Result of configlet fmt.
See exercism/meta#95 
Created at ROSSConf. /cc @kytrinyx

Reformat config files for reordering

---

config.json

I noticed that the progress bars in the 'concepts' section weren't updating and I informed that this was because the exercises don't have topics assigned to them. This isn't a complete fix, but it's a start.

Add topics to config file

---

config.json

Two_fer should be the second exercise.

Move two_fer to second position.

---

config.json

The 'Beer song' exercise is the main focus of the book: 99 bottles
(https://www.sandimetz.com/99bottles)
It would be good if users could access the tests and specification
without having to unlock it.

Unlock beer song

---

exercises/twelve-days/.meta/solutions/twelve_days.rb
exercises/twelve-days/README.md
exercises/twelve-days/song.txt

Update twelve-days to match specification

---

exercises/alphametics/alphametics_test.rb

Update `alphametics` tests to: `1.3.0 361cf3c`

alphametics: Regenerate Tests

---

exercises/anagram/anagram_test.rb

Update `anagram` tests to: `1.4.0 baaf092`

anagram: Regenerate Tests

---

docs/24pullrequests.md

I simply removed a sentence that was redundant in the information it was stating about submitting pull requests.

Removed redundant sentence

---

exercises/alphametics/.meta/solutions/alphametics_compact.rb
exercises/alphametics/alphametics_test.rb

@Insti [suggested](https://github.com/exercism/ruby/issues/849#issuecomment-431613956) that a pull request might be apropos.

A compact solution to alphametics.

---

exercises/high-scores/high_scores_test.rb

Very simple PR to bump the test version now that https://github.com/exercism/problem-specifications/pull/1378 has been merged.

high-scores: Regenerate tests

---

README.md

Addition of a table of contents to the readme, for an easier navigation experience.

documentation: table of contents to readme for easy nav

---

exercises/clock/clock_test.rb

Update `clock` tests to: `2.4.0 b344762`

clock: Regenerate Tests

---

exercises/luhn/luhn_test.rb

Update `luhn` tests to: `1.4.0 4a80663`

luhn: Regenerate Tests

---

exercises/phone-number/phone_number_test.rb

Update `phone-number` tests to: `1.6.1 fc57696`

phone-number: Regenerate Tests

---

exercises/bracket-push/bracket_push_test.rb

Update `bracket-push` tests to: `1.5.0 20dd164`

bracket-push: Regenerate Tests

---

exercises/hamming/hamming_test.rb

Update `hamming` tests to: `2.2.0 4c453c8`

hamming: Regenerate Tests

---

exercises/pythagorean-triplet/README.md
exercises/pythagorean-triplet/pythagorean_triplet_test.rb

**Pythagorean Triplet**: Updated `README.md` from the [problem-specifications](https://github.com/exercism/problem-specifications/blob/master/exercises/pythagorean-triplet/description.md) and added a test for the _sum = 1,000_ case.

pythagorean-triplet: update README.md and added test for the sum = 1,000 case

---

exercises/series/.meta/solutions/hints.md

In a different issue I'm going to propose to promote Series to a core exercise.
To make mentoring easier, this is adding some Ruby specific instructions to the Readme. 
We experimented with such Instructions in the High Scores readme, and it really helps improve the mentoring experience.

Add ruby specific hints for the Series Readme

---

exercises/ocr-numbers/.meta/hints.md

See this [discussion](https://exercism-team.slack.com/archives/CARVB5V0R/p1544794176021300) on Slack.

Ruby/OCR: add hints file with hint on trailing whitespace

---

config/maintainers.json

Adding myself to the maintainer list 😊

Add Pedro as a maintainer

---

config/maintainers.json

I've moved a few folks to 'alumni', as it's been 2 or 3 years since we've heard from
them.
I emailed each of the individuals in question.

Update maintainer config to reflect new reality

---

config.json
exercises/resistor-colors/.meta/generator/resistor_colors_case.rb
exercises/resistor-colors/.meta/solutions/resistor_colors.rb
exercises/resistor-colors/README.md
exercises/resistor-colors/resistor_colors_test.rb

Closes #938. The goal was to have something that passes the tests from https://github.com/exercism/problem-specifications/pull/1466 so we can start the conversation.
TODO:

resistor-colors: New exercise implementation

---

exercises/twelve-days/README.md

- Provide a more detailed explanation of the twelve days song for people who might not know it
- Clarify that song.txt is not to be used for the solution

Improve twelve-days exercise definition

---

config.json

The result of running `bin/configlet fmt .` on this repo. This is only a formatting change - no behavioral change is expected.

Format config.json using bin/configlet

---

config.json
exercises/resistor-color/.meta/generator/resistor_color_case.rb
exercises/resistor-color/.meta/solutions/resistor_color.rb
exercises/resistor-color/README.md
exercises/resistor-color/resistor_color_test.rb

Closes #970. Have a look at the canonical data [here](https://github.com/exercism/problem-specifications/tree/master/exercises/resistor-color). 🕺

resistor-color: New exercise

---

config.json

See https://github.com/exercism/ruby/pull/981/commits/76fd7236911f9833ed1f7547d9726877f6b58f00#r310752197

Revert unintended config.json change from #981

---

config.json

Reverts exercism/ruby#984
As intended via another PR.

Revert "Revert unintended config.json change from #981"

---

exercises/resistor-color-duo/.meta/solutions/resistor_color_duo.rb
exercises/resistor-color-duo/README.md
exercises/resistor-color-duo/resistor_color_duo_test.rb

Problem specifications PR for 2.1.0: https://github.com/exercism/problem-specifications/pull/1569
Mentor notes have already been merged here: https://github.com/exercism/website-copy/pull/1231

resistor-color-duo: Update exercise to 2.1.0

---

config.json

**(Updated from discussion)**
For our in-browser coding UI, we need need some settings that are track-specific. This is my first pass at what that might look like. 
There are two settings:
- `indent_style`: Should presses of the tab key add a tab character or x spaces. Can be "tab" or "space".
- `indent_size`: How far to indent when when you press the tab key.
So the net result of these two options in Ruby is that we add two spaces when someone presses tab, which I believe to be the normal default.
I'd appreciate feedback from @exercism/track-maintainers on the keys/structure, and also @exercism/ruby on the values for the Ruby track.
Note: I will probably merge this PR early, just so we can have *something* on master to develop against, but I don't intend that to be the end of the …

Add editor settings to config.json

---

bin/fetch-configlet

1028 update fetch configlet

---

docs/INSTALLATION.md

closes: #1025
/cc: @porkostomus

Official installation guides

---

exercises/darts/darts.rb

Add darts.rb file for Darts

---

config.json
exercises/microwave/.meta/solutions/microwave.rb
exercises/microwave/README.md
exercises/microwave/microwave.rb
exercises/microwave/microwave_test.rb

Hello there, 
I was recently warming up some chili and was thinking about the microwave timer and thought wouldn't that be a fun beginners exercism. Please consider for review my first exercism submission, 'Microwave'.

'Microwave' exercise

---

exercises/microwave/microwave_test.rb

Fix typo in microwave_test.rb

---

exercises/concept/conditionals-ternary/.meta/config.json

These files were missing from the v3 port. This should fix basic CI.

Add missing files

---

concepts/basics/about.md

Fix: Lines are ended by having a \n at the end.
Fix: markdown code blocks fixed

Concepts basics about

---

config.json

ref: #1099
I misunderstood the changes required from 1099.
Please confirm @ErikSchierboom

File Patterns corrected

---

exercises/practice/microwave/.docs/instructions.md
exercises/practice/microwave/.meta/config.json

Fixes https://github.com/exercism/ruby/issues/1116

Add microwave blurb and readme

---

exercises/concept/amusement-park-improvements/attendee.rb
exercises/concept/amusement-park/attendee.rb
exercises/concept/assembly-line/assembly_line.rb
exercises/concept/bird-count/bird_count.rb
exercises/concept/boutique-inventory-improvements/boutique_inventory.rb
exercises/concept/boutique-inventory/boutique_inventory.rb
exercises/concept/lasagna/lasagna.rb
exercises/concept/log-line-parser/log_line_parser.rb
exercises/concept/moviegoer/moviegoer.rb
exercises/concept/savings-account/savings_account.rb
exercises/concept/simple-calculator/simple_calculator.rb

Raise a string instead of a specific error

---

concepts/enumeration/about.md
concepts/exceptions/about.md
concepts/nil/about.md
docs/TESTS.md
exercises/concept/amusement-park-improvements/.docs/hints.md
exercises/concept/amusement-park/.docs/hints.md
exercises/concept/amusement-park/.docs/instructions.md
exercises/concept/amusement-park/.docs/introduction.md
exercises/concept/bird-count/.docs/hints.md
exercises/concept/bird-count/.docs/introduction.md
exercises/concept/boutique-inventory/.meta/exemplar.rb
exercises/concept/lasagna/.docs/hints.md
exercises/concept/lasagna/.docs/introduction.md
exercises/concept/log-line-parser/.docs/introduction.md
exercises/concept/simple-calculator/.meta/design.md
test/generator/exercise_case_test.rb

I just went through the first 4 concept exercises in Ruby on exercism.lol for the first time. I noticed a few tiny details that need improvement. I'm leaving my feedback in a form of a PR that already fixes those things. The commit history should describe well the changes I'm proposing. I'll revert anything you don't really want 🙂 in general:
- some random typos
- some hints not showing up because there were paragraphs between list items or because the task name was different than in instructions

Fix typos, broken links, hints not showing up etc.

---

exercises/concept/assembly-line/.docs/hints.md
exercises/concept/assembly-line/assembly_line_test.rb

Hi! I just solved this exercise for the first time and I had two problems that I'm trying to address in this PR:
1. Hints were missing (heading mismatch)
2. I made a mistake in the implementation of `production_rate_per_hour` but it wasn't caught by the tests for that method. It caused a failure in one of the tests of `working_items_per_minute` instead.

Assembly-line improvements

---

concepts/exceptions/about.md
concepts/exceptions/introduction.md
config.json
exercises/concept/moviegoer/.docs/hints.md
exercises/concept/moviegoer/.docs/instructions.md
exercises/concept/moviegoer/.docs/introduction.md

Hi! I just solved this exercise for the first time and I noticed some details that I would like to improve:
1. No hints. I tried to write some but my Ruby is very rusty so please review thoroughly.
2. The text about exceptions mentioned that exercise stubs raise `NotImplementedError`. This is no longer true.
3. Small typos in the introduction.

Moviegoer improvements

---

exercises/concept/log-line-parser/.meta/config.json
exercises/concept/moviegoer/.meta/config.json

There is an icon that first the exercise log-line-parser but it's called slightly differently.

Set icon for log-line-parser and moviegoer

---

exercises/concept/log-line-parser/log_line_parser_test.rb

rest_reformat to test_reformat.

---

exercises/concept/log-line-parser/.docs/introduction.md

Using `string` rather than `str` to keep the style of using full words for things that we write.

Contractions, abbreviations and whitespace, oh my.

---

exercises/practice/microwave/microwave_test.rb

Hi! Thank you very much for the task!
I was playing with Ruby track and found out that the task can be finished cause tests are broken.
https://exercism.org/tracks/ruby/exercises/microwave

Fix tests for the Microwave task

---

exercises/concept/amusement-park/.docs/introduction.md

To make the demo code work as expected, the instance variable names need to match.

Update introduction for amusement-park exercise

---

exercises/concept/bird-count/.meta/exemplar.rb

This brings the language of the code closer to telling the story of the problem.

Refer to birds, stick to the story.

---

exercises/concept/amusement-park/.docs/introduction.md

Remove extra "methods" in introduction.md

---

exercises/concept/amusement-park/.docs/introduction.md

Change number_of_wings to wings

---

exercises/concept/log-line-parser/.docs/instructions.md

implements changes proposed in #1202

changed instructions to be inline with tests and code stubs

---

config.json

This was the only exercise without practices/prerequisites.

microwave: add prerequisite

---

exercises/concept/savings-account/.docs/instructions.md

A positive number is greater than 0, a non-negative balance less than 1000 dollar includes a zero balance.

Fix a missconception

---

concepts/basics/introduction.md
exercises/concept/lasagna/.docs/introduction.md

- Update the Calculator call of multiply method num2 parameter

Ruby Basics Introduction.md typo #1230

---

exercises/practice/robot-name/.meta/config.json

Closes https://github.com/exercism/exercism/issues/6114

robot-name: disable test runner

---

exercises/concept/simple-calculator/.docs/instructions.md

Single line per sentence as the only change.

Simple calculator markdown guide compliance

---

exercises/concept/assembly-line/.docs/introduction.md

noticed this grammar mistake while doing the exercise, pretty sure "whole" needs "a" before it instead of "an". thanks!

fix grammar error "an" -> "a"

---

exercises/concept/boutique-inventory-improvements/.docs/instructions.md

I think that "previously" is the correct word here

Fix typo in boutique inventory improvements

---

exercises/concept/amusement-park-improvements/.docs/instructions.md

The instructions in the readme were unclear. I could not understand how I am supposed to implement it until I saw the argument name in `attendee.rb` file.

Amusement Park Improvement: Update instruction for `fits_ride?` method

---

README.md

Readme markdown style compliance

---

concepts/arrays/introduction.md

little oversight correction

---

concepts/modules/introduction.md

It seems like a typo but I'm not sure. Please have a look.

fix class's typo

---

exercises/concept/simple-calculator/.docs/hints.md

The hints were empty for this exercise and needed to be added in
order to help users.

Update simple calculator hints

---

.github/workflows/exercise-tests.yml
config.json
exercises/practice/kindergarten-garden/.docs/instructions.append.md

This was consider as an easy one, however this exercise involves
being knowledgeable in metaprogramming concepts as mentioned
by an user. Therefore we decided to bump up its difficulty level
to 4.

Bumps Kindergarten Garden exercise difficulty level

---

concepts/exceptions/about.md

Remove trailing white space where it has no meaning.

One sentence per line

---

exercises/practice/hello-world/GETTING_STARTED.md

Steps are adjusted, and reflect closer to what should happen when a
student starts with Hello World exercise in Ruby.

Getting Started for Hello World

---

exercises/practice/meetup/.meta/example.rb

Includes reorganizing to keep all private methods together.

Fix: year and number no longer public

---

exercises/practice/simple-linked-list/.meta/config.json

Sync simple-linked-list with problem-specifications

---

exercises/practice/simple-cipher/.meta/config.json

Sync simple-cipher with problem-specifications

---

exercises/practice/pig-latin/.meta/config.json

Sync pig-latin with problem-specifications

---

exercises/practice/food-chain/.meta/config.json

Sync food-chain with problem-specifications

---

exercises/practice/two-fer/.meta/config.json

Sync two-fer with problem-specifications

---

exercises/practice/connect/.meta/config.json

Sync connect with problem-specifications

---

exercises/practice/resistor-color-trio/.docs/instructions.md

Sync resistor-color-trio with problem-specifications

---

exercises/practice/binary/.meta/config.json

Sync binary with problem-specifications

---

exercises/practice/twelve-days/.docs/instructions.md
exercises/practice/twelve-days/.meta/config.json

Sync twelve-days with problem-specifications

---

exercises/practice/sieve/.docs/instructions.md

Sync sieve with problem-specifications

---

exercises/practice/secret-handshake/.docs/instructions.md

Sync secret-handshake with problem-specifications

---

exercises/practice/saddle-points/.docs/instructions.md

Sync saddle-points with problem-specifications

---

exercises/practice/resistor-color/.docs/instructions.md
exercises/practice/resistor-color/.meta/config.json

No test changes; just docs and metadata.

Sync resistor-color with problem-specifications

---

exercises/practice/pythagorean-triplet/.docs/instructions.md

Sync pythagorean-triplet with problem-specifications

---

exercises/practice/ocr-numbers/.docs/instructions.md

Sync ocr-numbers with problem-specifications

---

exercises/practice/minesweeper/.docs/instructions.md
exercises/practice/minesweeper/.meta/config.json

No test changes; just docs and metadata.

Sync minesweeper with problem-specifications

---

exercises/practice/meetup/.docs/instructions.md

Sync meetup with problem-specifications

---

exercises/practice/hello-world/.docs/instructions.md
exercises/practice/hello-world/.meta/config.json

No test changes; just docs and metadata.

Sync hello-world with problem-specifications

---

exercises/practice/grains/.docs/instructions.md

This is literally one whitespace change in the docs. One.

Sync grains with problem-specifications

---

exercises/practice/affine-cipher/.docs/instructions.md

There are no test changes, just docs.

Sync affine-cipher with problem-specifications

---

exercises/practice/acronym/.docs/instructions.md
exercises/practice/acronym/.meta/config.json

There are no test changes; only docs and metadata.

Sync acronym with problem-specifications

---

exercises/practice/nucleotide-count/.docs/instructions.md

Sync nucleotide-count with problem-specifications

---

exercises/practice/crypto-square/.docs/instructions.md

There are no test changes; just docs.

Sync crypto-square with problem-specifications

---

exercises/practice/atbash-cipher/.docs/instructions.md

There are no test changes; just docs.

Sync atbash-cipher with problem-specifications

---

exercises/practice/darts/.docs/instructions.md
exercises/practice/darts/.meta/config.json

There are no test changes; just docs and metadata.

Sync darts with problem-specifications

---

exercises/practice/dominoes/.docs/instructions.md

There are no test changes; just docs.

Sync dominoes with problem-specifications

---

exercises/practice/grep/.docs/instructions.md

Sync grep with problem-specifications

---

exercises/practice/isogram/.docs/instructions.md
exercises/practice/isogram/.meta/tests.toml
exercises/practice/isogram/isogram_test.rb

This syncs the docs and tests.toml from
problem-specifications, and regenerates the test suite.
This resulted in one new test.

Update isogram from problem-specifications

---

exercises/practice/all-your-base/.docs/instructions.md

There are no test changes; just docs.

Sync all-your-base with problem-specifications

---

exercises/practice/word-count/.meta/tests.toml
exercises/practice/word-count/word_count_test.rb

This has an additional test for yet another apostrophe case. Since we already have several cases for apostrophes it seems like this is a good choice to include.

Sync word-count with problem specifications

---

exercises/practice/triangle/.docs/instructions.md
exercises/practice/triangle/.meta/tests.toml
exercises/practice/triangle/triangle_test.rb

This has two new test cases that both make sense for our implementation.

Sync triangle with problem specifications

---

exercises/practice/phone-number/.docs/instructions.md
exercises/practice/phone-number/.meta/tests.toml
exercises/practice/phone-number/phone_number_test.rb

There were no new tests, but two of the tests were reimplemented to have slightly different data.

Sync phone number with problem-specifications

---

exercises/shared/.docs/debug.md

This is very rudimentary, but should be enough to let people start using the custom debug method.
Closes #1195

Add debug information for editor

---

exercises/practice/resistor-color-duo/.docs/instructions.md
exercises/practice/resistor-color-duo/.meta/tests.toml
exercises/practice/resistor-color-duo/resistor_color_duo_test.rb

We got new docs and two new tests.

Sync resistor-color-duo with problem-specifications

---

exercises/practice/say/.docs/instructions.md
exercises/practice/say/.meta/tests.toml
exercises/practice/say/say_test.rb

In the first commit I extracted the expected value into a variable for readability since some of the lines are really long.
In the second commit I ran configlet sync and then regenerated the test suite, which added a few tests.

Sync say with problem-specifications

---

exercises/practice/hamming/.docs/instructions.md
exercises/practice/hamming/.meta/tests.toml
exercises/practice/hamming/hamming_test.rb

The tests.toml had a number of reimplemented tests, but nothing that changes the exercise materially.

Sync hamming with problem-specifications

---

exercises/practice/isbn-verifier/.docs/instructions.md
exercises/practice/isbn-verifier/.meta/tests.toml
exercises/practice/isbn-verifier/isbn_verifier_test.rb

I synced the docs and tests, and regenerated the test suite.
We got a few renamed tests, and a couple of new ones.

Sync isbn-verifier with problem-specifications

---

exercises/practice/armstrong-numbers/.docs/instructions.md
exercises/practice/armstrong-numbers/.meta/tests.toml
exercises/practice/armstrong-numbers/armstrong_numbers_test.rb

I synced the docs and tests, and regenerated the test suite.
The test names changed, and there were a couple of new tests. One of them is for a very big number, which doesn't need any careful handling in Ruby.

Sync armstrong numbers

---

exercises/practice/luhn/.docs/instructions.md
exercises/practice/luhn/.meta/tests.toml
exercises/practice/luhn/luhn_test.rb

This adds several new tests, but doesn't introduce any changed requirements.

Sync luhn with problem-specifications

---

exercises/practice/prime-factors/.docs/instructions.md
exercises/practice/prime-factors/.meta/tests.toml
exercises/practice/prime-factors/prime_factors_test.rb

This updates docs and the tests.toml and regenerates the test suite, bringing in several new tests.
There tests do not change the requirements.

Sync prime-factors with problem-specifications

---

exercises/practice/matching-brackets/.docs/instructions.md
exercises/practice/matching-brackets/.meta/tests.toml
exercises/practice/matching-brackets/matching_brackets_test.rb

This updates the instructions and tests.toml and regenerates the test suite. There were three new tests, but no changes in requirements.

Sync matching-brackets with problem-specifications

---

exercises/practice/protein-translation/.docs/instructions.md
exercises/practice/protein-translation/.meta/tests.toml
exercises/practice/protein-translation/protein_translation_test.rb

The docs and tests.toml were updated, and I regenerated the test suite.
This brought in quite a few new tests, but it didn't change any requirements.

Sync protein-translation with problem-specifications

---

exercises/practice/largest-series-product/.docs/instructions.md
exercises/practice/largest-series-product/.meta/tests.toml
exercises/practice/largest-series-product/largest_series_product_test.rb

This syncs the docs and tests, and regenerates the test suite.
There was a reimplemented test, so nothing exciting to see here.

Sync largest-series-product with problem-specifications

---

exercises/practice/collatz-conjecture/.docs/instructions.md
exercises/practice/collatz-conjecture/.meta/config.json
exercises/practice/collatz-conjecture/.meta/tests.toml

This brings in new docs, metadata, and a couple of reimplemented tests to tests.toml.
Regenerating the test suite didn't change anything.

Sync collatz-conjecture with problem-specifications

---

exercises/practice/poker/.docs/instructions.md
exercises/practice/poker/.meta/example.rb
exercises/practice/poker/.meta/tests.toml
exercises/practice/poker/poker_test.rb

The docs and tests.toml were updated in the sync,
and I regenerated the test suite.
A number of new tests were brought in, one of which required a tweak to the example solution.

Sync poker with problem-specifications

---

exercises/practice/transpose/.docs/instructions.md
exercises/practice/transpose/.meta/tests.toml
exercises/practice/transpose/transpose_test.rb

The sync brought in new docs and a new test to tests.toml
When regenerating the test suite I removed some blank lines that I didn't feel were adding any readability.

Sync transpose with problem-specifications

---

exercises/practice/change/.docs/instructions.md
exercises/practice/change/.meta/config.json
exercises/practice/change/.meta/tests.toml
exercises/practice/change/change_test.rb

The sync brought in new docs and metadata, as well as an extra test in tests.toml.
I regenerated the tests, with no surprises.

Sync change with problem-specifications

---

exercises/practice/kindergarten-garden/.docs/instructions.md
exercises/practice/kindergarten-garden/.meta/tests.toml
exercises/practice/kindergarten-garden/kindergarten_garden_test.rb

The sync brought in new docs and added new tests to tests.toml.
The original test suite had grouped a lot of tests. Regenerating the tests created a lot more tests, but the example solution didn't need to be changed.

Sync kindergarten-garden with problem-specifications

---

exercises/practice/grade-school/.docs/instructions.md
exercises/practice/grade-school/.meta/config.json
exercises/practice/grade-school/.meta/example.rb
exercises/practice/grade-school/.meta/tests.toml
exercises/practice/grade-school/grade_school_test.rb

The upstream specification has undergone significant changes. This generates a new test suite based on the changed specification, and reimplements the sample solution to pass the new tests.

Reimplement grade-school based on problem-specifications

---

exercises/practice/queen-attack/.docs/instructions.md
exercises/practice/queen-attack/.meta/tests.toml
exercises/practice/queen-attack/queen_attack_test.rb

The sync brought in changes to the documentation, new titles for all the tests, and a new test.
The regenerated test suite didn't require any changes to the sample solution.

Sync queen-attack with problem-specifications

---

exercises/practice/complex-numbers/.docs/instructions.md
exercises/practice/complex-numbers/.meta/tests.toml
exercises/practice/complex-numbers/complex_numbers_test.rb

The sync brought in new docs as well as adding tests to tests.toml.
Regenerating the test suite was straight-forward; no surprises.

Sync complex-numbers with problem-specifications

---

.github/workflows/exercise-tests.yml

Remove operating system comments

---

exercises/practice/affine-cipher/.docs/instructions.md
exercises/practice/allergies/.docs/instructions.md
exercises/practice/bowling/.docs/instructions.md
exercises/practice/darts/.docs/instructions.md
exercises/practice/diamond/.docs/instructions.md
exercises/practice/food-chain/.docs/instructions.md
exercises/practice/grep/.docs/instructions.md
exercises/practice/hello-world/.docs/instructions.md
exercises/practice/house/.docs/instructions.md
exercises/practice/leap/.docs/instructions.md
exercises/practice/linked-list/.docs/instructions.md
exercises/practice/list-ops/.docs/instructions.md
exercises/practice/pig-latin/.docs/instructions.md
exercises/practice/protein-translation/.docs/instructions.md
exercises/practice/resistor-color-duo/.docs/instructions.md
exercises/practice/rna-transcription/.docs/instructions.md
exercises/practice/simple-cipher/.docs/instructions.md
exercises/practice/space-age/.docs/instructions.md
exercises/practice/two-bucket/.docs/instructions.md
exercises/practice/wordy/.docs/instructions.md
exercises/practice/zipper/.docs/instructions.md

This brings in recent improvements from problem-specifications.
Most of the changes are:
- normalizing urls to be https rather than http
- normalizing markdown to use hyphens for unordered list item bullets
- changing markdown to use one-sentence-per-line
There's also one place where we change a markdown comment so it doesn't
get parsed as a broken link reference.

Sync practice exercise docs

---

exercises/concept/locomotive-engineer/.docs/hints.md
exercises/concept/locomotive-engineer/.docs/instructions.md

Thanks to Carme Mias, also known as @carmemias, for reporting the
grammatical error, this corrects it.
ref: #1492

[Locomotive Engineer]: Grammar for a/an list

---

exercises/practice/saddle-points/.docs/instructions.md

https://github.com/exercism/problem-specifications/pull/2272

 saddle-points: Fix row values in instructions

---

Gemfile
Gemfile.lock

We were a few years out of date.

Upgrade rubocop to latest version

---

exercises/practice/leap/.meta/tests.toml

The tests.toml had tests in it that are not reflected
in the test suite.
Also, there was a typo in it, which is really weird.

Fix tests.toml for leap

---

exercises/practice/wordy/.meta/tests.toml

There were tests in the toml that have not yet
been implemented.

Fix wordy tests.toml

---

exercises/practice/sum-of-multiples/.meta/tests.toml

The tests.toml included a test that is not included in the
actual test suite.

Normalize sum-of-multiples tests.toml

---

exercises/concept/amusement-park-improvements/attendee_test.rb

As [discussed](https://forum.exercism.org/t/add-test-to-amusement-park-improvements/5948).

[Amusement Park Improvements]: Add test to match story

---

exercises/practice/kindergarten-garden/.docs/instructions.append.md

See a discussion over at [the forum](http://forum.exercism.org/t/dynamic-programming-in-kindergarten-garden/6609) for why the original text is not really correct. The suggested rephrasing was also discussed there.

[Kindergarten Garden] Fix a mention of dynamic programming.

---

exercises/practice/zipper/.meta/config.json

Test the new representer version key.

Update sample exercise to version to representer

---

concepts/symbols/.meta/config.json
concepts/symbols/about.md
concepts/symbols/introduction.md
concepts/symbols/links.json
config.json
exercises/concept/port-palermo/.docs/hints.md
exercises/concept/port-palermo/.docs/instructions.md
exercises/concept/port-palermo/.docs/introduction.md
exercises/concept/port-palermo/.meta/config.json
exercises/concept/port-palermo/.meta/design.md
exercises/concept/port-palermo/.meta/exemplar.rb
exercises/concept/port-palermo/port_palermo.rb
exercises/concept/port-palermo/port_palermo_test.rb

[New Concept]: Symbols

---

exercises/concept/chess-game/.docs/introduction.md

We are using the range constructor, it uses the range initializer.

Range constructor is used

---

exercises/practice/microwave/.docs/instructions.md

I always find this confusing and I think others do too. This aims to add clarity. I'm open to suggestions that improve it further.

Update Microwave Instructions

---

exercises/concept/boutique-inventory/.docs/introduction.md

Simple grammar error correction (the "to" is understood).
[Forum discussion](https://forum.exercism.org/t/update-boutique-inventory-introduction-md-simple-english-grammar-error-correction/10942/2).

[Boutique Inventory]: Update introduction.md

---

concepts/loops/links.json

Change old links, they were for Floats.
https://forum.exercism.org/t/update-loops-links-json/13095/3 for the discussion on the forums.

Update links for loops

---

config.json
exercises/practice/bottle-song/.docs/instructions.md
exercises/practice/bottle-song/.meta/config.json
exercises/practice/bottle-song/.meta/example.rb
exercises/practice/bottle-song/.meta/tests.toml
exercises/practice/bottle-song/bottle_song.rb
exercises/practice/bottle-song/bottle_song_test.rb

This exercise is intended to replace *beer song*, since that exercise is depricated (it will be done in a later pr). Replacing beer song is based on this issue: https://github.com/exercism/problem-specifications/issues/2066

[New Exercise]: Bottle Song

---

concepts/conditionals/about.md
concepts/conditionals/introduction.md

Tried to clear up the example. Text now matches condition and added the else case.
Discussion is located [here].
[here]: https://forum.exercism.org/t/confusing-unless-else-example-in-conditionals-concept/16293/7

Update unless / else example in conditionals concept

---

concepts/enumeration/about.md
concepts/enumeration/introduction.md

https://forum.exercism.org/t/update-enumeration-intro/17477

update block format to match output, and remove trailing white spaces

---

exercises/concept/blackjack/.docs/instructions.md

I opened a topic about this [here](https://forum.exercism.org/t/suggestion-for-blackjack-exercise-instructions/17857), and I didn't sense any pushback, so I figured I would create a PR. This is similar to a change made in the Go track in [this PR](https://github.com/exercism/go/pull/2855).

Clarify blackjack instructions
